// Command ftv-graphql-pins writes the Rego module that pins the digest of
// every bundled GraphQL schema.
//
// The schemas travel with the PDP image, not with the policy bundle, so
// the bundle pins them (FTV GraphQL profile, Sections 7.1 and 7.3): the
// policy denies an evaluation whose schema digest differs from the pin.
//
//	ftv-graphql-pins <catalog-dir> <out.rego>
package main

import (
	"fmt"
	"os"
	"strings"

	ftvgraphql "gbo-demo/ftv-graphql-mapper"
)

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: ftv-graphql-pins <catalog-dir> <out.rego>")
		os.Exit(2)
	}
	catalog, err := ftvgraphql.LoadCatalog(os.DirFS(os.Args[1]))
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
	module, err := render(catalog)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(os.Args[2], []byte(module), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}

// render returns the Rego module, formatted as opa fmt leaves it. A service
// whose schema does not load gets no pin: generation fails instead.
func render(catalog *ftvgraphql.Catalog) (string, error) {
	var b strings.Builder
	b.WriteString(`# Code generated by scripts/gen-graphql-pins.sh from schemas/pdp-mirror. DO NOT EDIT.
#
# The digest of the GraphQL schema the PDP loads per FSC service. The
# schemas travel with the PDP image, not with this bundle, so the bundle
# pins them, and the policy can refuse an evaluation against another one.
package dvtp.gbo.graphql_schemas

digests := {
`)
	for _, name := range catalog.Names() {
		s, _ := catalog.Service(name)
		if s.Err != nil {
			return "", fmt.Errorf("service %s: %w", name, s.Err)
		}
		fmt.Fprintf(&b, "\t%q: %q,\n", name, s.Schema.Digest)
	}
	b.WriteString("}\n")
	return b.String(), nil
}
