# Code generated by scripts/gen-graphql-pins.sh from schemas/pdp-mirror. DO NOT EDIT.
#
# The digest of the GraphQL schema the PDP loads per FSC service. The
# schemas travel with the PDP image, not with this bundle, so the bundle
# pins them, and the policy can refuse an evaluation against another one.
package dvtp.gbo.graphql_schemas

digests := {
	"bri": "sha256:e890aab3ea7d5988debf46f561517d85420f11fc5fe0eb0bf45cbaed77b48b72",
	"brp": "sha256:635dbe16fa2152cf1c838bc458e840f8892466b7ab7e79587d112975437494ce",
	"lvg": "sha256:f22ff9c1ee6bcd5b23a458cc5e79bd5a4ece3f074ea6a7717b980d57c6a6879a",
}
