# Code generated by scripts/gen-graphql-pins.sh from schemas/pdp-mirror. DO NOT EDIT.
#
# The digest of the GraphQL schema the PDP loads per FSC service. The
# schemas travel with the PDP image, not with this bundle, so the bundle
# pins them, and the policy can refuse an evaluation against another one.
package dvtp.gbo.graphql_schemas

digests := {
	"bri": "sha256:d17d09a9d36a5843f341f57ece804b805067841812566edc704a7090d53a143f",
	"brp": "sha256:a7c8a24594ef5c886dbfbbf0fe45a93bbca2f2c99fda2a9e5ca03212579521b3",
	"lvg": "sha256:b4ddfbe4e60d24f9c83ac35aa1fb055a5894d531fd37e3f5372d312f9acc9d3b",
}
