server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }
    location /api/dev/ {
        proxy_pass http://dev-portal-backend:4007/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_cache off;
    }
    location /portal-api/ {
        proxy_pass http://consent-portal-backend:4005/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Authorization $http_authorization;
        proxy_buffering off;
        proxy_cache off;
    }
    location /dvtp-api/ {
        proxy_pass http://dienstverlener-backend:4006/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_cache off;
    }
    location /eudi-api/ {
        proxy_pass http://eudi-adapter:4009/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_cache off;
    }
    location /jaeger-api/ {
        proxy_pass http://jaeger:16686/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_cache off;
    }
}
