apiVersion: v1
kind: Service
metadata:
  name: {{ include "gbo-app.fullname" . }}
  labels:
    {{- include "gbo-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.containerPort }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "gbo-app.selectorLabels" . | nindent 4 }}
