// Package main — FSC-txlog access for the dev-portal.
//
// Queries each FSC-org's txlog REST API via
// `GET /v1/logs?group_id=<>&transaction_ids=<uuid>`. For a given
// Fsc-Transaction-Id (generated by eudi-adapter and propagated by FSC
// through the whole chain) both orgs return an outgoing and/or incoming
// record — enough to render the chain hop-by-hop.
//
// Demo shortcut: dev-portal-backend calls the txlog-api directly using
// each org's intra-org internal-cert as client-cert. This implies that
// dev-portal sits "inside" the org, which is not technically true. A
// production setup would go through the peer-facing manager /v1/logs
// with a peer-cert (per the Logius fsc-logging spec).
package main

import (
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"sync"
	"time"
)

// txlogLogRecord — subset of the fsc-logging.yaml logRecord shape. Only
// the fields the dev-portal currently renders; extend as needed. Full
// shape lives in open-fsc txlog-api/ports/rest/api/openapi.yaml.
type txlogLogRecord struct {
	TransactionID string          `json:"transaction_id"`
	GroupID       string          `json:"group_id"`
	Direction     string          `json:"direction"`
	GrantHash     string          `json:"grant_hash"`
	ServiceName   string          `json:"service_name"`
	Source        json.RawMessage `json:"source"`
	Destination   json.RawMessage `json:"destination"`
	CreatedAt     json.RawMessage `json:"created_at"`
}

// txlogListResponse — shape of GET /v1/logs.
type txlogListResponse struct {
	Records []txlogLogRecord `json:"records"`
}

// peerResult wraps a single peer's records plus an optional error, so the
// UI can show that a peer was down without breaking the whole lookup.
type peerResult struct {
	Peer    string           `json:"peer"`
	Records []txlogLogRecord `json:"records"`
	Error   string           `json:"error,omitempty"`
}

// handleFscTxlog: GET /api/fsc/txlog/<transactionId>
// Queries all configured peers in parallel and returns a record list per
// peer. Returns [] when no peers are configured (fsc-infra not running).
func handleFscTxlog(cfg config) http.HandlerFunc {
	// Per-peer client cache — building the TLS config is expensive and the
	// certs do not change at runtime.
	clients := map[string]*http.Client{}
	var mu sync.Mutex

	getClient := func(p fscTxlogPeer) (*http.Client, error) {
		mu.Lock()
		defer mu.Unlock()
		if c, ok := clients[p.Name]; ok {
			return c, nil
		}
		cert, err := tls.LoadX509KeyPair(p.Cert, p.Key)
		if err != nil {
			return nil, fmt.Errorf("load %s client-cert: %w", p.Name, err)
		}
		pool := x509.NewCertPool()
		caPEM, err := os.ReadFile(p.CA)
		if err != nil {
			return nil, fmt.Errorf("read %s CA: %w", p.Name, err)
		}
		if !pool.AppendCertsFromPEM(caPEM) {
			return nil, fmt.Errorf("parse %s CA", p.Name)
		}
		c := &http.Client{
			Timeout: 5 * time.Second,
			Transport: &http.Transport{
				TLSClientConfig: &tls.Config{
					Certificates: []tls.Certificate{cert},
					RootCAs:      pool,
				},
			},
		}
		clients[p.Name] = c
		return c, nil
	}

	fetchPeer := func(p fscTxlogPeer, txID string) peerResult {
		client, err := getClient(p)
		if err != nil {
			return peerResult{Peer: p.Name, Error: err.Error()}
		}
		q := url.Values{}
		q.Set("group_id", cfg.FscGroupID)
		q.Add("transaction_ids", txID)
		endpoint := p.URL + "/v1/logs?" + q.Encode()
		resp, err := client.Get(endpoint)
		if err != nil {
			return peerResult{Peer: p.Name, Error: err.Error()}
		}
		defer resp.Body.Close()
		if resp.StatusCode != http.StatusOK {
			return peerResult{Peer: p.Name, Error: fmt.Sprintf("http %d", resp.StatusCode)}
		}
		var body txlogListResponse
		if err := json.NewDecoder(resp.Body).Decode(&body); err != nil {
			return peerResult{Peer: p.Name, Error: err.Error()}
		}
		return peerResult{Peer: p.Name, Records: body.Records}
	}

	return func(w http.ResponseWriter, r *http.Request) {
		corsHeaders(w)
		if r.Method == http.MethodOptions {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		if r.Method != http.MethodGet {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		txID := r.URL.Path[len("/fsc/txlog/"):]
		if txID == "" {
			http.Error(w, "transaction_id required", http.StatusBadRequest)
			return
		}
		if len(cfg.FscTxlogPeers) == 0 {
			writeJSON(w, http.StatusOK, map[string]any{
				"transaction_id": txID,
				"peers":          []peerResult{},
				"note":           "fsc-infra not configured (no FSC_TXLOG_*_URL env vars set)",
			})
			return
		}

		results := make([]peerResult, len(cfg.FscTxlogPeers))
		var wg sync.WaitGroup
		for i, p := range cfg.FscTxlogPeers {
			wg.Add(1)
			go func(i int, p fscTxlogPeer) {
				defer wg.Done()
				results[i] = fetchPeer(p, txID)
			}(i, p)
		}
		wg.Wait()

		writeJSON(w, http.StatusOK, map[string]any{
			"transaction_id": txID,
			"peers":          results,
		})
	}
}
