// Package main implements the demo "dienstverlener-backend" — the server-side
// component of a fictive data consumer (Hypotheek-BV). It owns the FSC-client
// boundary: the browser frontend only talks to this backend, never to FSC or
// PEP directly. In a production deployment this service would hold mTLS keys
// and FSC Outway config.
//
// Endpoint: POST /api/dvtp/query  {consent_id, scope_id?, belastingjaren?}
//
//	→ FSC Outway: pick contract by grant-link, sign token, open mTLS to Inway
//	→ FSC Inway proxy: forward GraphQL query (with PI as bsn variable)
//	   ↳ PEP → OPA → BSNk Transform → graphql-server
//	→ return  {allowed, data | reason, trace_id}
package main

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
	"go.opentelemetry.io/otel/propagation"
	"go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.24.0"
	"go.opentelemetry.io/otel/trace"
)

type config struct {
	Port             string
	OrgOIN           string
	OrgSector        string
	DevPortalBackend string
	OutwayURL        string
	OutwayPath       string
	ConsentURL       string
	HTTPClient       *http.Client
}

const upstreamRequestTimeout = 30 * time.Second

func loadConfig() config {
	return config{
		Port:             getEnv("PORT", "4006"),
		OrgOIN:           getEnv("ORG_OIN", "99999999900000000300"),
		OrgSector:        getEnv("ORG_SECTOR", "hypotheekverlener"),
		DevPortalBackend: getEnv("DEV_PORTAL_BACKEND_URL", ""),
		OutwayURL:        getEnv("OUTWAY_URL", "http://hv-outway:8080"),
		OutwayPath:       getEnv("OUTWAY_PATH", "/bri/graphql"),
		ConsentURL:       getEnv("CONSENT_URL", "http://consent-register:4002"),
		HTTPClient:       &http.Client{Timeout: upstreamRequestTimeout},
	}
}

func getEnv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

// ── HTTP helpers ─────────────────────────────────────────────────────────

func corsHeaders(w http.ResponseWriter) {
	w.Header().Set("Access-Control-Allow-Origin", "*")
	w.Header().Set("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
	w.Header().Set("Access-Control-Allow-Headers", "Content-Type")
}

func writeJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

// ── Query handler ────────────────────────────────────────────────────────

type queryRequest struct {
	ConsentID      string   `json:"consent_id"`
	ScopeID        string   `json:"scope_id,omitempty"`
	Belastingjaren []int    `json:"belastingjaren,omitempty"`
	Fields         []string `json:"fields,omitempty"`
}

type queryResponse struct {
	Allowed bool            `json:"allowed"`
	Data    json.RawMessage `json:"data,omitempty"`
	Reason  string          `json:"reason,omitempty"`
	TraceID string          `json:"trace_id"`
	// DeniedYears lists the requested belastingjaren the consent does not
	// cover. The backend intersects requested years with the consent's
	// scopes and only queries the covered ones (a query for an
	// unconsented year would deny the whole request); the frontend
	// renders the denied years greyed out.
	DeniedYears []int `json:"denied_years,omitempty"`
}

// newFscTransactionID returns a UUID v7 used as both the FSC-transaction-id
// and the OTel-trace-id — one identifier end-to-end across the chain. The
// FSC-Outway strictly validates v7, so v4 is not accepted.
func newFscTransactionID() string {
	u, err := uuid.NewV7()
	if err != nil {
		return uuid.NewString()
	}
	return u.String()
}

// fscTxIDCtxKey stashes the Fsc-Transaction-Id generated by the middleware
// so handleQuery can reuse it (instead of minting a second UUID — which
// would break the correlation between the response trace_id and OPA's
// input.trace_id).
type fscTxIDCtxKeyType struct{}

var fscTxIDCtxKey = fscTxIDCtxKeyType{}

// withFscTraceContext ties the OTel trace-id to the Fsc-Transaction-Id
// (UUID v7, 128 bits — exactly the OTel trace-id format). Without it the
// backend span gets a fresh random trace-id while the PDP reconstructs its
// trace from the FSC-transaction-id, and the two never match — breaking
// decision-log lookups by trace_id (dev-portal /explain). Same pattern as
// the eudi-adapter. Sets the Traceparent header BEFORE otelhttp extracts
// the parent context.
func withFscTraceContext(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fscTxID := newFscTransactionID()
		if r.Header.Get("Traceparent") == "" {
			traceHex := strings.ReplaceAll(fscTxID, "-", "")
			spanHex := randomSpanIDHex()
			if len(traceHex) == 32 && spanHex != "" {
				r.Header.Set("Traceparent", "00-"+traceHex+"-"+spanHex+"-01")
			}
		}
		r = r.WithContext(context.WithValue(r.Context(), fscTxIDCtxKey, fscTxID))
		next.ServeHTTP(w, r)
	})
}

// randomSpanIDHex returns 8 bytes of hex — a valid OTel span-id.
func randomSpanIDHex() string {
	var b [8]byte
	if _, err := rand.Read(b[:]); err != nil {
		return ""
	}
	return hex.EncodeToString(b[:])
}

// fetchConsentPI resolves the pseudonym (PI) and granted scopes for a
// given consent-id from the consent-register. The PI, not the consent-id,
// travels in transit inside the GraphQL query variable; the sidecar at the
// source resolves PI→BSN. The consent-register URL comes from config.
func fetchConsentPI(ctx context.Context, client *http.Client, consentURL, consentID string) (string, []string, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, consentURL+"/consents/"+consentID, nil)
	if err != nil {
		return "", nil, err
	}
	otel.GetTextMapPropagator().Inject(ctx, propagation.HeaderCarrier(req.Header))
	resp, err := client.Do(req)
	if err != nil {
		return "", nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", nil, fmt.Errorf("consent-register HTTP %d", resp.StatusCode)
	}
	var c struct {
		PI     string   `json:"pi"`
		Status string   `json:"status"`
		Scopes []string `json:"scopes"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&c); err != nil {
		return "", nil, err
	}
	if c.Status != "ACTIVE" {
		return "", nil, fmt.Errorf("consent %s status=%s (not ACTIVE)", consentID, c.Status)
	}
	if c.PI == "" {
		return "", nil, fmt.Errorf("consent %s has no PI", consentID)
	}
	return c.PI, c.Scopes, nil
}

// consentedYears extracts the belastingjaren covered by granted scopes of
// the form bd:ib:<year>.
func consentedYears(scopes []string) []int {
	var years []int
	for _, s := range scopes {
		rest, ok := strings.CutPrefix(s, "bd:ib:")
		if !ok {
			continue
		}
		if y, err := strconv.Atoi(rest); err == nil {
			years = append(years, y)
		}
	}
	return years
}

// intersectYears splits the requested years into the ones covered by the
// consent (queryable) and the rest (denied).
func intersectYears(requested, consented []int) (allowed, denied []int) {
	set := make(map[int]bool, len(consented))
	for _, y := range consented {
		set[y] = true
	}
	for _, y := range requested {
		if set[y] {
			allowed = append(allowed, y)
		} else {
			denied = append(denied, y)
		}
	}
	return allowed, denied
}

// buildQuery renders the GraphQL query against the BD bron-schema. The
// query uses `bsn` as its argument, but the actual value passed in the
// variable is a PI. This matches the EUDI shape exactly. The sidecar at
// the source resolves PI→BSN (subject_id_type=pseudonym), so the source
// always sees a BSN. The `$bsn` variable name is kept explicit so the PDP
// AST-parser picks it up as the bsn argument.
//
// The belastingjaren filter travels INSIDE the query: the bron returns
// all aangiften for a person, so per-year consent is only enforceable by
// policy when the PDP can see the requested years (rule DVT0001's
// years_in_scopes check). Default = the two most recent years.
//
// `fields` is an optional field-selection; empty = default set of 5
// fields. Bedrag-fields (verzamelinkomen, box*Inkomen) only exist on the
// concrete AangifteIH type, so they are wrapped in an inline fragment
// with their scalar leaves selected. Scenarios that want to test
// out-of-scope fields (e.g. box2Inkomen) set fields explicitly.
func buildQuery(jaren []int, fields []string) string {
	if len(jaren) == 0 {
		jaren = []int{2024, 2025}
	}
	if len(fields) == 0 {
		fields = []string{"belastingjaar", "verzamelinkomen", "box1Inkomen", "status", "indieningsdatum"}
	}
	var plain, bedragen []string
	for _, f := range fields {
		if bedragFields[f] {
			bedragen = append(bedragen, f+" { waarde valuta }")
		} else {
			plain = append(plain, f)
		}
	}
	selection := strings.Join(plain, " ")
	if len(bedragen) > 0 {
		selection += " ... on AangifteIH { " + strings.Join(bedragen, " ") + " }"
	}
	jarenJSON, _ := json.Marshal(jaren)
	return fmt.Sprintf(`query($bsn: BSN!) { ingeschrevenPersoon(bsn: $bsn) { heeftBelastingjaarAangifte(belastingjaren: %s) { %s } } }`,
		string(jarenJSON), selection)
}

// bedragFields are the AangifteIH fields of type Bedrag in the BD schema.
var bedragFields = map[string]bool{
	"verzamelinkomen": true,
	"box1Inkomen":     true,
	"box2Inkomen":     true,
	"box3Inkomen":     true,
}

func handleQuery(cfg config) http.HandlerFunc {
	client := cfg.HTTPClient
	if client == nil {
		client = &http.Client{Timeout: upstreamRequestTimeout}
	}

	return func(w http.ResponseWriter, r *http.Request) {
		corsHeaders(w)
		if r.Method == http.MethodOptions {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		if r.Method != http.MethodPost {
			writeJSON(w, http.StatusMethodNotAllowed, map[string]string{"error": "method not allowed"})
			return
		}

		var req queryRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			writeJSON(w, http.StatusBadRequest, map[string]string{"error": "invalid request body"})
			return
		}
		if req.ConsentID == "" {
			writeJSON(w, http.StatusBadRequest, map[string]string{"error": "consent_id is required"})
			return
		}
		if req.ScopeID == "" {
			req.ScopeID = "bd:ib:2025"
		}

		tracer := otel.Tracer("dienstverlener-backend")
		ctx, span := tracer.Start(r.Context(), "dvtp.query")
		defer span.End()
		log := loggerFromCtx(ctx)

		// The backend talks to a real FSC-Outway.
		//
		// Step 1 — Consent-lookup: fetch the PI + granted scopes for this
		// consent-id from the consent-register. The PI travels in the query;
		// the consent-id does not.
		pi, scopes, err := fetchConsentPI(ctx, client, cfg.ConsentURL, req.ConsentID)
		if err != nil {
			log.Warn("consent-lookup failed", "consent_id", req.ConsentID, "err", err.Error())
			writeJSON(w, http.StatusForbidden, map[string]any{
				"allowed":  false,
				"reason":   "consent_lookup_failed: " + err.Error(),
				"trace_id": traceIDFromSpan(span),
			})
			return
		}

		// Per-year consent. Two consumer profiles:
		//   - Browser flow (dienstverlener-mock): intersect requested years
		//     with the consent's scopes and only query the covered ones,
		//     so the citizen sees exactly the years they consented to and
		//     the rest comes back as denied_years (greyed out in the UI).
		//   - Dev-portal (X-Demo-Source): send the query exactly as
		//     requested — the portal exists to demonstrate raw policy
		//     outcomes, so a year outside the consent must produce the
		//     policy deny (YEAR_NOT_COVERED) with a full trace, not a
		//     client-side pre-filter.
		jaren := req.Belastingjaren
		if len(jaren) == 0 {
			jaren = []int{2024, 2025}
		}
		fromDevPortal := r.Header.Get("X-Demo-Source") == "dev-portal"
		queryable := jaren
		var deniedYears []int
		if !fromDevPortal {
			queryable, deniedYears = intersectYears(jaren, consentedYears(scopes))
		}
		traceID := traceIDFromSpan(span)

		// Nothing consented (browser flow only): skip the FSC call (an
		// empty year filter would fail policy fail-closed anyway) and
		// report every requested year as denied.
		if len(queryable) == 0 {
			log.Info("no requested years covered by consent", "consent_id", req.ConsentID, "trace_id", traceID)
			emptyData, _ := json.Marshal(map[string]any{
				"data": map[string]any{
					"ingeschrevenPersoon": map[string]any{"heeftBelastingjaarAangifte": []any{}},
				},
			})
			resp := queryResponse{Allowed: true, Data: emptyData, TraceID: traceID, DeniedYears: deniedYears}
			writeJSON(w, http.StatusOK, resp)
			return
		}

		// Step 2 — POST to the Outway at /bri/graphql. The body is pure
		// GraphQL, with variables.bsn = PI (the sidecar at the source
		// substitutes it back to BSN). No separate token-fetch is needed:
		// the Outway picks a contract by grant-link, signs the token
		// internally, and opens mTLS to the Inway.
		query := buildQuery(queryable, req.Fields)
		vars := map[string]string{"bsn": pi}
		proxyBody, _ := json.Marshal(map[string]any{
			"query":     query,
			"variables": vars,
		})
		proxyReq, _ := http.NewRequestWithContext(ctx, http.MethodPost,
			cfg.OutwayURL+cfg.OutwayPath, bytes.NewReader(proxyBody))
		proxyReq.Header.Set("Content-Type", "application/json")
		// Untrusted context-header: X-GBO-Scope carries the requested scope.
		// (There is no X-GBO-Flow header; flow is a grant-property.)
		proxyReq.Header.Set("X-GBO-Scope", req.ScopeID)
		// X-GBO-Consent-Id references the consent this request is backed
		// by. The PDP does its PIP lookup on exactly this record, so
		// revoking it deterministically denies this query — a different
		// consent for the same PI does not rescue it. The constraint-
		// binding rule proves the query's PI matches this consent's PI.
		proxyReq.Header.Set("X-GBO-Consent-Id", req.ConsentID)
		// Fsc-Transaction-Id doubles as the OTel-trace-id — one identifier
		// end-to-end across the FSC chain. The middleware already minted it
		// and tied the span trace-id to it; fall back to a fresh UUID only
		// when the middleware is not in the chain (unit tests).
		fscTxID, _ := ctx.Value(fscTxIDCtxKey).(string)
		if fscTxID == "" {
			fscTxID = newFscTransactionID()
		}
		proxyReq.Header.Set("Fsc-Transaction-Id", fscTxID)
		span.SetAttributes(attribute.String("gbo.fsc.transaction_id", fscTxID))
		otel.GetTextMapPropagator().Inject(ctx, propagation.HeaderCarrier(proxyReq.Header))

		proxyResp, err := client.Do(proxyReq)
		if err != nil {
			log.Error("fsc outway call failed", "err", err.Error())
			writeJSON(w, http.StatusBadGateway, queryResponse{
				Allowed: false,
				Reason:  "fsc_outway_call_failed: " + err.Error(),
				TraceID: traceID,
			})
			return
		}
		defer proxyResp.Body.Close()
		proxyRespBody, _ := io.ReadAll(proxyResp.Body)

		// Skip backend-side history-post when the dev-portal is the trigger;
		// its frontend already logs the run (X-Demo-Source header signals,
		// already read above).

		// 200 = ALLOW with data, 403 = DENY with reason, other = error
		if proxyResp.StatusCode == http.StatusOK {
			log.Info("query allowed", "consent_id", req.ConsentID, "trace_id", traceID)
			resp := queryResponse{
				Allowed:     true,
				Data:        json.RawMessage(proxyRespBody),
				TraceID:     traceID,
				DeniedYears: deniedYears,
			}
			writeJSON(w, http.StatusOK, resp)
			if cfg.DevPortalBackend != "" && !fromDevPortal {
				go postUseHistory(cfg.DevPortalBackend, req, resp, traceID)
			}
			return
		}

		var denyResp struct {
			Allowed bool   `json:"allowed"`
			Reason  string `json:"reason"`
		}
		_ = json.Unmarshal(proxyRespBody, &denyResp)
		if denyResp.Reason == "" {
			denyResp.Reason = fmt.Sprintf("upstream_error: status %d", proxyResp.StatusCode)
		}
		log.Info("query denied", "consent_id", req.ConsentID, "reason", denyResp.Reason, "trace_id", traceID)
		resp := queryResponse{
			Allowed: false,
			Reason:  denyResp.Reason,
			TraceID: traceID,
		}
		writeJSON(w, http.StatusOK, resp)
		if cfg.DevPortalBackend != "" && !fromDevPortal {
			go postUseHistory(cfg.DevPortalBackend, req, resp, traceID)
		}
	}
}

// Best-effort: log the use-query to dev-portal-backend history. Failures
// are silent — the afnemer-flow is the primary concern.
func postUseHistory(devURL string, req queryRequest, qResp queryResponse, traceID string) {
	outcome := "deny"
	if qResp.Allowed {
		outcome = "allow"
	}
	entry := map[string]any{
		"scenario_name": fmt.Sprintf("Afnemer · use · scope %s", req.ScopeID),
		"tab":           "use",
		"payload": map[string]any{
			"consent_id":     req.ConsentID,
			"scope_id":       req.ScopeID,
			"belastingjaren": req.Belastingjaren,
			"fields":         req.Fields,
		},
		"trace_id":   traceID,
		"outcome":    outcome,
		"consent_id": req.ConsentID,
		"response":   qResp,
	}
	body, _ := json.Marshal(entry)
	httpReq, err := http.NewRequest(http.MethodPost, devURL+"/history", bytes.NewReader(body))
	if err != nil {
		slog.Warn("dev-portal-backend history post: build failed", "err", err.Error())
		return
	}
	httpReq.Header.Set("Content-Type", "application/json")
	client := &http.Client{Timeout: 3 * time.Second}
	resp, err := client.Do(httpReq)
	if err != nil {
		slog.Warn("dev-portal-backend history post: unreachable", "err", err.Error())
		return
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 300 {
		slog.Warn("dev-portal-backend history post: bad status", "status", resp.StatusCode)
	}
}

func traceIDFromSpan(span trace.Span) string {
	sc := span.SpanContext()
	if !sc.IsValid() {
		return ""
	}
	return sc.TraceID().String()
}

// ── OTel setup ───────────────────────────────────────────────────────────

func setupTracing(ctx context.Context, serviceName string) (func(context.Context) error, error) {
	endpoint := os.Getenv("OTEL_EXPORTER_OTLP_ENDPOINT")
	if endpoint == "" {
		return func(context.Context) error { return nil }, nil
	}
	exp, err := otlptracegrpc.New(ctx,
		otlptracegrpc.WithEndpoint(endpoint),
		otlptracegrpc.WithInsecure(),
	)
	if err != nil {
		return nil, err
	}
	res, _ := resource.New(ctx, resource.WithAttributes(semconv.ServiceName(serviceName)))
	tp := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(exp, sdktrace.WithBatchTimeout(100*time.Millisecond)),
		sdktrace.WithResource(res),
	)
	otel.SetTracerProvider(tp)
	otel.SetTextMapPropagator(propagation.TraceContext{})
	return tp.Shutdown, nil
}

// ── Main ─────────────────────────────────────────────────────────────────

// newMux builds the routing tree for the backend. Extracted from main so
// integration tests can wire the handlers to an httptest.Server (with
// stub OutwayURL + ConsentURL in cfg) without starting the real listener.
func newMux(cfg config) *http.ServeMux {
	mux := http.NewServeMux()
	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		writeJSON(w, http.StatusOK, map[string]string{"status": "ok"})
	})
	mux.HandleFunc("/api/dvtp/query", handleQuery(cfg))
	return mux
}

func main() {
	cfg := loadConfig()
	slog.SetDefault(slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelInfo}).
		WithAttrs([]slog.Attr{slog.String("service", "dienstverlener-backend")})))

	ctx := context.Background()
	shutdown, err := setupTracing(ctx, "dienstverlener-backend")
	if err != nil {
		slog.Error("otel setup failed", "err", err)
	}
	defer func() {
		shutCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		_ = shutdown(shutCtx)
	}()

	mux := newMux(cfg)
	// Middleware order: withFscTraceContext wraps otelhttp — the header
	// mutation must happen before otelhttp extracts the parent context.
	handler := withFscTraceContext(otelhttp.NewHandler(withAccessLog(mux), "dienstverlener-backend"))
	addr := ":" + cfg.Port
	slog.Info("dienstverlener-backend starting",
		"addr", addr, "outway", cfg.OutwayURL+cfg.OutwayPath, "org_oin", cfg.OrgOIN, "sector", cfg.OrgSector,
		"req_id", uuid.New().String())
	if err := http.ListenAndServe(addr, handler); err != nil {
		slog.Error("server stopped", "err", err)
	}
}
