// Package main implements the EUDI adapter — a bridge between nl-wallet's
// issuance-server and the PEP/OpenFTV-PDP/graphql-server chain.
//
// Role:
//  1. Receives a POST from the issuance-server (contains disclosed PID with BSN)
//  2. POSTs through the transport selected during source onboarding. The
//     currently implemented profile is FSC: no explicit token fetch or Bearer. The
//     adapter sends the grant hash resolved from the contract; Outway opens mTLS to the target Inway,
//     and presents the token from the contract.
//  3. The Inway receives the request, validates the token, and forwards
//     to the backend service (PDP as AuthZen endpoint).
//  4. PEP dispatches on the flow (BSN comes from the disclosed PID; no
//     consent fetch, no BSNk transform).
//  5. On PDP ALLOW: the bron answers; the adapter formats
//     the response as an IssuableDocument list.
//
// Every credential type is supplied by an onboarded source. The source-owned
// metadata, fetched through its onboarded endpoint, defines the GraphQL endpoint,
// query, its parameters and the claim
// mapping; the adapter contains no source-specific query or formatter.
//
// DELIBERATELY OUT OF SCOPE for V1:
//   - PID signature verification (BSN is trusted)
//   - Wallet-cert check
//   - State between requests (each request is stateless)
//
// LOG HYGIENE: log the bare minimum. BSN prefix + attestation-type + trace-id.
// No data body. The adapter sits IN transit for sensitive data; full data
// minimization is a policy question left open.
package main

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	ldv "gbo-demo/ldv-client"
	"io"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/google/uuid"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
	"go.opentelemetry.io/otel/propagation"
	"go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.24.0"
	"go.opentelemetry.io/otel/trace"

	"gbo-demo/eudi-adapter/internal/gbosimplev1"
)

// fscTxIDCtxKey stashes the Fsc-Transaction-Id generated by the middleware
// so callViaFSC can reuse it (instead of minting a second UUID).
type fscTxIDCtxKeyType struct{}

var fscTxIDCtxKey = fscTxIDCtxKeyType{}

// readHeaderTimeout bounds how long a client may take to send its request
// headers, so a stalled connection cannot hold a handler open.
const readHeaderTimeout = 10 * time.Second

// shutdownTimeout bounds the drain after SIGTERM: stop accepting, let
// in-flight requests finish, then close whatever is left.
const shutdownTimeout = 15 * time.Second

type config struct {
	Port      string
	OutwayURL string

	// These fields are resolved from the active onboarding record before
	// serving begins; they are deliberately not separate deployment settings.
	SourceDataTransport           string
	SourceDataFSCServiceReference string
	SourceDataFSCGrantHash        string
	SourceMetadataSourceID        string
	SourceMetadataOIN             string
	SourceMetadataTypeID          string
	SourceMetadataVersion         string
	SourceMetadataDefinition      sourceAttestationDefinition
	SourceMetadataVCT             string
	SourceMetadataVCTIntegrity    string
	SourceMetadataFreshUntil      time.Time
	SourceMetadataStaleUntil      time.Time

	SourceRegistryDatabaseURL string
	SourceRegistrySchema      string
	SourceRegistryRefresh     time.Duration
}

func loadConfig() config {
	refresh, err := time.ParseDuration(getEnv("SOURCE_REGISTRY_REFRESH_INTERVAL", "5s"))
	if err != nil || refresh <= 0 {
		refresh = 5 * time.Second
	}
	return config{
		Port:                      getEnv("PORT", "4009"),
		OutwayURL:                 getEnv("FSC_OUTWAY_URL", "http://edi-outway:8080"),
		SourceRegistryDatabaseURL: os.Getenv("SOURCE_REGISTRY_DATABASE_URL"),
		SourceRegistrySchema:      getEnv("SOURCE_REGISTRY_SCHEMA", "source_registry"),
		SourceRegistryRefresh:     refresh,
	}
}

func getEnv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

// issuanceServerRequest supports the two disclosure shapes used by the
// issuance integration:
//   - `attributes.urn:eudi:pid:nl:1.bsn` (nested, real PID sd-jwt)
//   - `attributes.bsn` (flat, test shape)
//
// We decode as `map[string]any` so both shapes can be scanned.
type issuanceServerRequest []struct {
	Attestations []struct {
		AttestationType string         `json:"attestation_type"`
		Attributes      map[string]any `json:"attributes"`
	} `json:"attestations"`
	ID string `json:"id"`
}

// extractBSN scans the attributes map for a BSN: first nested under the PID
// namespace, then flat.
func extractBSN(attrs map[string]any) string {
	if nested, ok := attrs["urn:eudi:pid:nl:1"].(map[string]any); ok {
		if s, ok := nested["bsn"].(string); ok {
			return s
		}
	}
	if s, ok := attrs["bsn"].(string); ok {
		return s
	}
	// Fallback: any one-level-deeper map with "bsn".
	for _, v := range attrs {
		if m, ok := v.(map[string]any); ok {
			if s, ok := m["bsn"].(string); ok {
				return s
			}
		}
	}
	return ""
}

// attestation is the generic shape consumed by the issuance-server. It
// expects a flat array without an envelope; credential metadata is resolved
// from the generated issuance configuration.
type attestation struct {
	AttestationType string         `json:"attestation_type"`
	Attributes      map[string]any `json:"attributes"`
	Format          string         `json:"format"`
	ID              string         `json:"id"`
}

// proxyRequest is the GraphQL body that FSC forwards to the source. Trusted
// authorization context, including the flow, comes from the FSC token.
type proxyRequest struct {
	Query     string         `json:"query"`
	Variables map[string]any `json:"variables,omitempty"`
}

// graphqlResponse only inspects the protocol-level error envelope. Projection
// of the data body is fully driven by the activated source metadata.
type graphqlResponse struct {
	Errors []map[string]any `json:"errors,omitempty"`
}

type sourceQueryPlan struct {
	ServiceReference string
	Endpoint         string
	Query            string
	Variables        map[string]any
}

type fscResult struct {
	Raw []byte
}

// handleSourceAttestation is the only issuance path for onboarded types. The
// route selects an activated source/type; concrete parameter values come from
// the issuance request URL and are validated against the source declaration.
func handleSourceAttestation(cfg config, client *http.Client, runtime sourceMetadataRuntime, logbook *issuanceLogbook) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		now := time.Now()
		// Two Dataverwerkingen happen below: reading the BSN out of the
		// disclosed PID, and assembling the attestation from what the source
		// returned. Both are GBO's own, both are logged, and neither delivers
		// if its record is not confirmed.
		extractionStart := time.Now().UTC()
		var recording issuanceRecording
		resolved := cfg
		var metadata *activeSourceMetadata
		var err error
		if activated, ok := runtime.(interface {
			currentSource(time.Time) (*activeSourceMetadata, config, error)
		}); ok {
			metadata, resolved, err = activated.currentSource(now)
		} else {
			metadata, err = runtime.current(now)
		}
		if err != nil {
			logSourceAttestationError(r, "metadata", err)
			http.Error(w, "source metadata unavailable", http.StatusServiceUnavailable)
			return
		}
		if r.PathValue("sourceID") != metadata.SourceID || r.PathValue("typeID") != metadata.TypeID {
			http.NotFound(w, r)
			return
		}
		if metadata.CacheState != "" {
			w.Header().Set("X-GBO-Metadata-Cache", metadata.CacheState)
		}
		body, err := io.ReadAll(io.LimitReader(r.Body, 4<<20))
		if err != nil {
			logSourceAttestationError(r, "read_request", err)
			http.Error(w, "invalid issuance request", http.StatusBadRequest)
			return
		}
		var request issuanceServerRequest
		if err := json.Unmarshal(body, &request); err != nil || len(request) == 0 || len(request[0].Attestations) == 0 {
			if err == nil {
				err = fmt.Errorf("issuance request contains no disclosed attestation")
			}
			logSourceAttestationError(r, "decode_request", err)
			http.Error(w, "invalid PID disclosure", http.StatusBadRequest)
			return
		}
		bsn := extractBSN(request[0].Attestations[0].Attributes)
		if bsn == "" {
			logSourceAttestationError(r, "extract_subject", fmt.Errorf("disclosed PID contains no BSN"))
			http.Error(w, "no BSN in disclosed PID", http.StatusBadRequest)
			return
		}
		// Logged before the source is called: a request that cannot be logged
		// must not reach the bronhouder at all.
		if logbook != nil {
			recording, err = logbook.logPIDExtraction(r.Context(), r, bsn, extractionStart, metadata.SourceID, metadata.TypeID)
			if err != nil {
				http.Error(w, "the PID disclosure could not be logged; refusing the request", http.StatusInternalServerError)
				return
			}
		}
		plan, err := metadata.queryPlan(bsn, r.URL.Query())
		if err != nil {
			logSourceAttestationError(r, "parameters", err)
			http.Error(w, "invalid attestation parameters", http.StatusBadRequest)
			return
		}
		trace.SpanFromContext(r.Context()).SetAttributes(
			attribute.String("gbo.source_id", metadata.SourceID),
			attribute.String("gbo.source_oin", metadata.SourceOIN),
			attribute.String("gbo.type_id", metadata.TypeID),
		)
		result, err := callSource(r.Context(), client, resolved, plan)
		if err != nil {
			logSourceAttestationError(r, "source_request", err)
			http.Error(w, "source request failed", http.StatusBadGateway)
			return
		}
		assemblyStart := time.Now().UTC()
		projection, err := metadata.project(result.Raw)
		if err != nil {
			logSourceAttestationError(r, "projection", err)
			http.Error(w, "source response could not be projected", http.StatusBadGateway)
			return
		}
		if projection.Outcome == gbosimplev1.OutcomeNoData {
			http.Error(w, "source has no data for this subject and parameters", http.StatusNotFound)
			return
		}
		// The attestation exists now; it does not leave this process until
		// the logbook has said so.
		if logbook != nil {
			if err := logbook.logAttestationAssembly(r.Context(), recording, assemblyStart,
				metadata.SourceID, metadata.TypeID, metadata.SourceOIN, len(projection.Claims)); err != nil {
				http.Error(w, "the attestation could not be logged; withholding it", http.StatusInternalServerError)
				return
			}
		}
		// nl-wallet turns attestation_type into the credential's vct and
		// computes vct#integrity from the installed Type Metadata bytes. Both
		// are internal claims and must not be supplied as ordinary attributes.
		documents := []attestation{{
			AttestationType: metadata.VCT,
			Attributes:      projection.Claims,
			Format:          "dc+sd-jwt",
			ID:              uuid.NewString(),
		}}
		w.Header().Set("Content-Type", "application/json")
		if err := json.NewEncoder(w).Encode(documents); err != nil {
			slog.Error("encode source attestation response", "err", err.Error())
		}
	}
}

func logSourceAttestationError(r *http.Request, stage string, err error) {
	slog.Error("source attestation request failed",
		"stage", stage,
		"source_id", r.PathValue("sourceID"),
		"type_id", r.PathValue("typeID"),
		"err", err.Error(),
	)
}

type sourceRuntimeBinding struct {
	config  config
	runtime sourceMetadataRuntime
}

// newFscTransactionID returns a UUID **v7** (time-ordered) — the
// FSC-Outway explicitly validates v7 and rejects v4 with
// INVALID_LOG_RECORD_ID.
func newFscTransactionID() (string, error) {
	u, err := uuid.NewV7()
	if err != nil {
		return "", err
	}
	return u.String(), nil
}

// withFscTraceContext — middleware that runs BEFORE otelhttp and ties the
// FSC standard identifier (Fsc-Transaction-Id, UUID v7) to the OTel
// trace-id. Rationale: UUID v7 is 128 bits — exactly the format of an
// OTel trace-id — and FSC propagates it through the whole chain
// (including to the authz-service as X-Request-Id). By making our
// trace-id equal to this correlator, the adapter span, graphql span, and
// pdp span end up in the same Jaeger trace automatically, without
// patching FSC's context.Background() behavior in the AuthZen plugin.
//
// The middleware sets the Traceparent header on the incoming request;
// otelhttp reads it and uses it as the parent context for the root span.
// The UUID itself is stashed in the request context so callViaFSC can
// set it as the Fsc-Transaction-Id header on the outway call (same
// value, no second UUID). If the caller already sent a Traceparent
// (e.g. an issuance-server with OTel), we leave it alone — the flow
// then hangs off the existing trace and we only mint the FSC-tx-id for
// FSC propagation.
func withFscTraceContext(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fscTxID, err := newFscTransactionID()
		if err == nil {
			// If no traceparent is present, tie the trace-id to the UUID.
			if r.Header.Get("Traceparent") == "" {
				traceHex := strings.ReplaceAll(fscTxID, "-", "")
				spanHex := randomSpanIDHex()
				if len(traceHex) == 32 && spanHex != "" {
					r.Header.Set("Traceparent", "00-"+traceHex+"-"+spanHex+"-01")
				}
			}
			r = r.WithContext(context.WithValue(r.Context(), fscTxIDCtxKey, fscTxID))
		}
		next.ServeHTTP(w, r)
	})
}

// randomSpanIDHex returns 8 bytes of hex — a valid OTel span-id.
func randomSpanIDHex() string {
	var b [8]byte
	if _, err := rand.Read(b[:]); err != nil {
		return ""
	}
	return hex.EncodeToString(b[:])
}

// callViaFSC posts the source-owned query to the data service selected by the
// activated onboarding record.
// The activation pins the data contract's grant-hash. The adapter sends that
// hash explicitly so the Outway uses exactly the contract that was reviewed
// and activated for this source and type.
//
// The Outway opens mTLS to the Inway (from the contract) and sets
// Fsc-Authorization: Bearer <token> itself. The Inway validates and
// forwards to the backend service. On DENY: 403 + reason.
//
// Flow selection is not sent by the adapter: the provider's FSC Manager puts
// the trusted, service-specific flow in the validated access token.
func callSource(ctx context.Context, client *http.Client, cfg config, plan sourceQueryPlan) (fscResult, error) {
	switch cfg.SourceDataTransport {
	case sourceTransportFSC:
		return callViaFSC(ctx, client, cfg, plan)
	case sourceTransportUnsecured:
		return callUnsecuredSource(ctx, client, plan)
	default:
		return fscResult{}, fmt.Errorf("unsupported source data transport %q", cfg.SourceDataTransport)
	}
}

func callUnsecuredSource(ctx context.Context, client *http.Client, plan sourceQueryPlan) (fscResult, error) {
	if plan.ServiceReference != "" {
		return fscResult{}, fmt.Errorf("unsecured source GraphQL plan must not contain a service reference")
	}
	if err := validateAbsoluteUnsecuredEndpoint(plan.Endpoint); err != nil {
		return fscResult{}, fmt.Errorf("active unsecured source GraphQL endpoint: %w", err)
	}
	body, _ := json.Marshal(proxyRequest{Query: plan.Query, Variables: plan.Variables})
	request, err := http.NewRequestWithContext(ctx, http.MethodPost, plan.Endpoint, bytes.NewReader(body))
	if err != nil {
		return fscResult{}, err
	}
	request.Header.Set("Content-Type", "application/json")
	otel.GetTextMapPropagator().Inject(ctx, propagation.HeaderCarrier(request.Header))
	response, err := doSourceRequest(client, request, true)
	if err != nil {
		return fscResult{}, err
	}
	defer response.Body.Close()
	responseBody, _ := io.ReadAll(response.Body)
	if response.StatusCode >= http.StatusMultipleChoices && response.StatusCode < http.StatusBadRequest {
		return fscResult{}, fmt.Errorf("unsecured source redirect is not allowed")
	}
	if response.StatusCode != http.StatusOK {
		return fscResult{}, fmt.Errorf("unsecured source status %d", response.StatusCode)
	}
	var graphql graphqlResponse
	if err := json.Unmarshal(responseBody, &graphql); err != nil {
		return fscResult{}, fmt.Errorf("decode graphql response: %w", err)
	}
	if len(graphql.Errors) > 0 {
		return fscResult{}, fmt.Errorf("graphql errors: %v", graphql.Errors)
	}
	return fscResult{Raw: responseBody}, nil
}

func callViaFSC(ctx context.Context, client *http.Client, cfg config, plan sourceQueryPlan) (fscResult, error) {
	if cfg.SourceDataFSCServiceReference == "" {
		return fscResult{}, fmt.Errorf("active source has no data FSC service reference")
	}
	if cfg.SourceDataFSCGrantHash == "" {
		return fscResult{}, fmt.Errorf("active source has no data FSC grant hash")
	}
	if plan.ServiceReference != cfg.SourceDataFSCServiceReference {
		return fscResult{}, fmt.Errorf("active source GraphQL service %q does not match contracted service %q", plan.ServiceReference, cfg.SourceDataFSCServiceReference)
	}
	if err := validateAbsoluteURLPath(plan.Endpoint); err != nil {
		return fscResult{}, fmt.Errorf("active source GraphQL endpoint: %w", err)
	}

	body, _ := json.Marshal(proxyRequest{Query: plan.Query, Variables: plan.Variables})

	endpoint := strings.TrimRight(cfg.OutwayURL, "/") + plan.Endpoint
	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(body))
	if err != nil {
		return fscResult{}, err
	}
	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("Fsc-Grant-Hash", cfg.SourceDataFSCGrantHash)
	// Reuse the Fsc-Transaction-Id that the middleware already generated
	// and that also forms the trace-id. That way trace-id ==
	// Fsc-Transaction-Id — a single identifier across the whole chain
	// (adapter -> FSC txlog -> pdp span). If the context does not carry
	// it (e.g. this function is called directly without the middleware),
	// fall back to a fresh UUID.
	fscTxID, _ := ctx.Value(fscTxIDCtxKey).(string)
	if fscTxID == "" {
		gen, err := newFscTransactionID()
		if err != nil {
			return fscResult{}, fmt.Errorf("generate Fsc-Transaction-Id: %w", err)
		}
		fscTxID = gen
	}
	httpReq.Header.Set("Fsc-Transaction-Id", fscTxID)
	trace.SpanFromContext(ctx).SetAttributes(attribute.String("gbo.fsc.transaction_id", fscTxID))
	otel.GetTextMapPropagator().Inject(ctx, propagation.HeaderCarrier(httpReq.Header))

	resp, err := client.Do(httpReq)
	if err != nil {
		return fscResult{}, err
	}
	defer resp.Body.Close()
	respBody, _ := io.ReadAll(resp.Body)

	if resp.StatusCode == http.StatusForbidden {
		var denied struct {
			Reason string `json:"reason"`
		}
		_ = json.Unmarshal(respBody, &denied)
		return fscResult{}, fmt.Errorf("denied by policy: %s", denied.Reason)
	}
	if resp.StatusCode != http.StatusOK {
		return fscResult{}, fmt.Errorf("fsc proxy status %d: %s", resp.StatusCode, string(respBody))
	}

	var out graphqlResponse
	if err := json.Unmarshal(respBody, &out); err != nil {
		return fscResult{}, fmt.Errorf("decode graphql response: %w", err)
	}
	if len(out.Errors) > 0 {
		return fscResult{}, fmt.Errorf("graphql errors: %v", out.Errors)
	}
	return fscResult{Raw: respBody}, nil
}

func initTracer(ctx context.Context) (func(context.Context) error, error) {
	endpoint := getEnv("OTEL_EXPORTER_OTLP_ENDPOINT", "otel-collector:4317")
	serviceName := getEnv("OTEL_SERVICE_NAME", "eudi-adapter")
	exp, err := otlptracegrpc.New(ctx,
		otlptracegrpc.WithEndpoint(endpoint),
		otlptracegrpc.WithInsecure(),
	)
	if err != nil {
		return nil, err
	}
	res, err := resource.New(ctx, resource.WithAttributes(semconv.ServiceName(serviceName)))
	if err != nil {
		return nil, err
	}
	tp := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(exp, sdktrace.WithBatchTimeout(100*time.Millisecond)),
		sdktrace.WithResource(res),
	)
	otel.SetTracerProvider(tp)
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(
		propagation.TraceContext{},
		propagation.Baggage{},
	))
	return tp.Shutdown, nil
}

// fatal logs and ends the process. main is the only place in this service
// that exits; everything else returns an error.
func fatal(msg string, err error) {
	slog.Error(msg, "err", err.Error())
	os.Exit(1)
}

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	if handled, err := runIssuanceReleaseCommand(ctx, os.Args[1:], os.Stdout, os.Stderr); handled {
		if err != nil {
			fatal("issuance Source Release materialization failed", err)
		}
		return
	}
	if handled, err := runSourceRegistryMigrateCommand(ctx, os.Args[1:], os.Stdout, os.Stderr); handled {
		if err != nil {
			fatal("source registry migration failed", err)
		}
		return
	}
	if handled, err := runSourceRegistryOperationsCommand(ctx, os.Args[1:], os.Stdout, os.Stderr); handled {
		if err != nil {
			fatal("Source Registry operation failed", err)
		}
		return
	}
	if handled, err := runReconcileCommand(ctx, os.Args[1:], defaultReconcileDependencies()); handled {
		if err != nil {
			fatal("source reconciliation failed", err)
		}
		return
	}
	if handled, err := runOnboardingCommand(ctx, os.Args[1:], defaultOnboardingDependencies()); handled {
		if err != nil {
			fatal("source onboarding failed", err)
		}
		return
	}
	cfg := loadConfig()
	if cfg.SourceRegistryDatabaseURL == "" {
		fatal("Source Registry configuration missing", fmt.Errorf("SOURCE_REGISTRY_DATABASE_URL is required"))
	}
	shutdown, err := initTracer(ctx)
	if err != nil {
		slog.Error("tracer init failed", "err", err.Error())
		os.Exit(1)
	}
	defer func() { _ = shutdown(ctx) }()

	client := &http.Client{
		Timeout:   10 * time.Second,
		Transport: otelhttp.NewTransport(http.DefaultTransport),
	}
	registry, err := openRuntimeSourceRegistry(ctx, cfg)
	if err != nil {
		fatal("open Source Registry", err)
	}
	defer registry.Close()

	// Either this adapter is part of GBO's LDV chain and cannot start without
	// its logbook, or it is not and writes no records.
	ldvClient, err := ldv.New(ldv.Config{
		ServiceName:  getEnv("OTEL_SERVICE_NAME", "eudi-adapter"),
		LogbookURL:   os.Getenv("LDV_LOGBOOK_URL"),
		WriteToken:   os.Getenv("LDV_WRITE_TOKEN"),
		PseudonymKey: os.Getenv("LDV_SUBJECT_PSEUDONYM_KEY"),
	})
	if err != nil {
		fatal("configuring the logboek client", err)
	}
	logbook := newIssuanceLogbook(ldvClient, parseNextLogbooks(os.Getenv("LDV_NEXT_LOGBOOK_IDS")))
	if ldvClient == nil {
		slog.Warn("no LDV_LOGBOOK_URL configured; this adapter writes no Logboek Dataverwerkingen records")
	}

	runtimeHandler := http.Handler(newSourceReleaseRuntimeMux(ctx, cfg, client, registry, logbook))
	// Middleware order: withFscTraceContext wraps otelhttp — the header
	// mutation must happen before otelhttp extracts the parent context.
	srv := &http.Server{
		Addr:              ":" + cfg.Port,
		Handler:           withFscTraceContext(otelhttp.NewHandler(runtimeHandler, "eudi-adapter")),
		ReadHeaderTimeout: readHeaderTimeout,
	}
	slog.Info("eudi-adapter starting", "addr", srv.Addr, "outway", cfg.OutwayURL)
	// Previously this logged and returned, so a failure to bind exited 0 and
	// looked like a clean shutdown to the orchestrator.
	serve(srv)
}

// serve runs the server until the process is asked to stop, then drains it.
// Without this a SIGTERM (docker compose down, a Kubernetes rollout) killed
// in-flight requests outright.
func serve(srv *http.Server) {
	go func() {
		if err := srv.ListenAndServe(); !errors.Is(err, http.ErrServerClosed) {
			fatal("listen and serve", err)
		}
	}()
	slog.Info("listening", "addr", srv.Addr)

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	<-ctx.Done()
	stop()

	slog.Info("shutting down")
	drainCtx, cancel := context.WithTimeout(context.Background(), shutdownTimeout)
	defer cancel()
	if err := srv.Shutdown(drainCtx); err != nil {
		slog.Warn("drain did not finish; closing remaining connections", "err", err.Error())
		_ = srv.Close()
	}
}
