// Package main implements the EUDI adapter — a bridge between nl-wallet's
// issuance-server and the PEP/PDP/OPA/graphql-server chain.
//
// Role:
//  1. Receives a POST from the issuance-server (contains disclosed PID with BSN)
//  2. POSTs to the FSC-Outway — no explicit token fetch, no Bearer. Outway
//     resolves the path prefix to a grant, opens mTLS to the target Inway,
//     and presents the token from the contract.
//  3. The Inway receives the request, validates the token, and forwards
//     to the backend service (PDP as AuthZen endpoint).
//  4. PEP dispatches on flow="eudi:attestation" (BSN comes from the
//     disclosed PID; no consent fetch, no BSNk transform).
//  5. On OPA ALLOW: PEP forwards the query to graphql-server; the adapter
//     formats the response as an IssuableDocument list.
//
// Transport is uniform with the DvTP flow (both via FSC); the access basis
// still differs (PID vs consent). OIN authenticates the actor and the path,
// not the per-request authorization.
//
// DELIBERATELY OUT OF SCOPE for V1:
//   - PID signature verification (BSN is trusted)
//   - Wallet-cert check
//   - Multi-attestation support (only the income declaration)
//   - State between requests (each request is stateless)
//
// LOG HYGIENE: log the bare minimum. BSN prefix + attestation-type + trace-id.
// No data body. The adapter sits IN transit for sensitive data; full data
// minimization is a policy question left open.
package main

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/google/uuid"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
	"go.opentelemetry.io/otel/propagation"
	"go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.24.0"
	"go.opentelemetry.io/otel/trace"
)

// fscTxIDCtxKey stashes the Fsc-Transaction-Id generated by the middleware
// so callViaFSC can reuse it (instead of minting a second UUID).
type fscTxIDCtxKeyType struct{}

var fscTxIDCtxKey = fscTxIDCtxKeyType{}

type config struct {
	Port        string
	OutwayURL   string
	IssuerOIN   string
	CatalogPath string
}

func loadConfig() config {
	return config{
		Port:        getEnv("PORT", "4009"),
		OutwayURL:   getEnv("FSC_OUTWAY_URL", "http://edi-outway:8080"),
		IssuerOIN:   getEnv("ISSUER_OIN", "00000004000000004000"),
		CatalogPath: getEnv("USECASE_CATALOG_PATH", "/config/usecase_catalog.json"),
	}
}

func getEnv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

// Usecase is a catalog entry — one per (attestation-type × parameter-set).
// The same attestation_type can have multiple entries (e.g. one per tax
// year); path-based routing (path-key = usecase-key) selects the active
// entry. The GraphQL query is built from the catalog; scope is forwarded
// as X-GBO-Scope to the PEP.
//
// OutwayPath is the FSC-Outway grant-link path for this source+service.
// Multiple usecases may share the same path as long as they consume the
// same FSC service — a single contract covers all of them (e.g. all three
// tax years via /bri/). A different source means a different path
// (e.g. /pid/ for RvIG).
type Usecase struct {
	AttestationType string `json:"attestation_type"`
	Scope           string `json:"scope"`
	Belastingjaren  []int  `json:"belastingjaren"`
	OutwayPath      string `json:"outway_path"`
	Note            string `json:"note,omitempty"`
}

type Catalog struct {
	Usecases map[string]Usecase `json:"usecases"`
}

func loadCatalog(path string) (*Catalog, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read catalog: %w", err)
	}
	var c Catalog
	if err := json.Unmarshal(data, &c); err != nil {
		return nil, fmt.Errorf("parse catalog: %w", err)
	}
	if len(c.Usecases) == 0 {
		return nil, fmt.Errorf("catalog has no usecases")
	}
	return &c, nil
}

// buildQuery builds a GraphQL query for the usecase against the BD
// bron-schema. The schema has no belastingjaren argument — the bron
// returns all aangiften for the person and the adapter selects the
// usecase's tax year from the response.
func buildQuery(u Usecase) string {
	return `query($bsn: BSN!) {
  ingeschrevenPersoon(bsn: $bsn) {
    heeftBelastingjaarAangifte {
      belastingjaar status indieningsdatum
      ... on AangifteIH {
        verzamelinkomen { waarde valuta }
        box1Inkomen { waarde valuta }
        box2Inkomen { waarde valuta }
        box3Inkomen { waarde valuta }
      }
    }
  }
}`
}

// issuanceServerRequest — a real disclosure can carry the BSN in two
// places (reverse-engineered from bri-mock.rs::extract_bsn):
//   - `attributes.urn:eudi:pid:nl:1.bsn` (nested, real PID sd-jwt)
//   - `attributes.bsn` (flat, test shape)
//
// We decode as `map[string]any` so both shapes can be scanned.
type issuanceServerRequest []struct {
	Attestations []struct {
		AttestationType string         `json:"attestation_type"`
		Attributes      map[string]any `json:"attributes"`
	} `json:"attestations"`
	ID string `json:"id"`
}

// extractBSN scans the attributes map for a BSN. It follows the same
// pattern as bri-mock.rs::extract_bsn: first nested under the PID
// namespace, then flat.
func extractBSN(attrs map[string]any) string {
	if nested, ok := attrs["urn:eudi:pid:nl:1"].(map[string]any); ok {
		if s, ok := nested["bsn"].(string); ok {
			return s
		}
	}
	if s, ok := attrs["bsn"].(string); ok {
		return s
	}
	// Fallback: any one-level-deeper map with "bsn".
	for _, v := range attrs {
		if m, ok := v.(map[string]any); ok {
			if s, ok := m["bsn"].(string); ok {
				return s
			}
		}
	}
	return ""
}

// attestation matches 1:1 the shape returned by bri-mock (reverse-
// engineered via curl). The issuance-server expects a flat array — no
// envelope; metadata (CA, issuer_uri, validity) is pulled by the
// issuance-server itself from its own config.
type attestation struct {
	AttestationType string         `json:"attestation_type"`
	Attributes      map[string]any `json:"attributes"`
	Format          string         `json:"format"`
	ID              string         `json:"id"`
}

// proxyRequest is the pure GraphQL body that the FSC-Inway forwards 1:1
// to the PEP's /evaluate endpoint. All context lives in HTTP headers:
//   - Authorization: Bearer <FSC-token>   -> Inway validates + propagates
//   - X-GBO-Scope: bd:ib:2025              -> PDP hint (untrusted)
//   - X-GBO-Flow: eudi:attestation         -> PEP dispatch (untrusted)
//
// BSN is already in the query variables (`$bsn`); no separate body field.
type proxyRequest struct {
	Query     string         `json:"query"`
	Variables map[string]any `json:"variables,omitempty"`
}

// graphqlResponse: on ALLOW the PEP forwards the graphql-server body 1:1.
// The BD bron-schema nests aangiften under the person; the interface list
// holds AangifteIH objects (decoded loosely — attributes are picked by
// name downstream).
type graphqlResponse struct {
	Data struct {
		IngeschrevenPersoon *struct {
			HeeftBelastingjaarAangifte []map[string]any `json:"heeftBelastingjaarAangifte"`
		} `json:"ingeschrevenPersoon"`
	} `json:"data"`
	Errors []map[string]any `json:"errors,omitempty"`
}

// handleAttestation is the per-usecase handler that the issuance-server
// calls via attestation_url_config.base_url. The usecase key comes from
// the mux registration (per path); all parameters (scope, tax year,
// attestation-type) come from the catalog entry — nothing is hard-coded
// in the adapter code.
func handleAttestation(cfg config, client *http.Client, usecaseKey string, uc Usecase) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		body, err := io.ReadAll(io.LimitReader(r.Body, 4<<20))
		if err != nil {
			http.Error(w, "read body: "+err.Error(), http.StatusBadRequest)
			return
		}

		var req issuanceServerRequest
		if err := json.Unmarshal(body, &req); err != nil {
			slog.Error("parse issuance-server request", "err", err.Error(), "raw_len", len(body))
			http.Error(w, "invalid request", http.StatusBadRequest)
			return
		}
		if len(req) == 0 || len(req[0].Attestations) == 0 {
			slog.Error("no attestation in disclosure", "raw_body", string(body))
			http.Error(w, "no PID attestation in disclosure", http.StatusBadRequest)
			return
		}

		// V1: take the first PID attestation. The BSN is trusted.
		bsn := extractBSN(req[0].Attestations[0].Attributes)
		if bsn == "" {
			attrKeys := make([]string, 0, len(req[0].Attestations[0].Attributes))
			for k := range req[0].Attestations[0].Attributes {
				attrKeys = append(attrKeys, k)
			}
			slog.Error("no BSN in disclosed PID", "usecase", usecaseKey, "attr_keys", attrKeys)
			http.Error(w, "no BSN in disclosed PID", http.StatusBadRequest)
			return
		}
		slog.Info("adapter received disclosure",
			"usecase", usecaseKey,
			"bsn_prefix", safePrefix(bsn),
			"attestation_type", uc.AttestationType,
			"scope", uc.Scope,
			"belastingjaren", uc.Belastingjaren,
		)

		// Policy check + data fetch via FSC -> PEP -> PDP -> OPA -> graphql.
		// Scope + query come from the catalog entry.
		aangiften, err := callViaFSC(r.Context(), client, cfg, bsn, uc)
		if err != nil {
			slog.Error("fsc call failed", "usecase", usecaseKey, "err", err.Error())
			http.Error(w, err.Error(), http.StatusBadGateway)
			return
		}
		aangifte := selectAangifte(aangiften, uc.Belastingjaren)
		if aangifte == nil {
			http.Error(w, "no aangifte found for BSN and belastingjaar", http.StatusNotFound)
			return
		}

		docs := formatAsIssuableDocuments(aangifte, uc)
		w.Header().Set("Content-Type", "application/json")
		if err := json.NewEncoder(w).Encode(docs); err != nil {
			slog.Error("encode response", "err", err.Error())
		}
	}
}

// newFscTransactionID returns a UUID **v7** (time-ordered) — the
// FSC-Outway explicitly validates v7 and rejects v4 with
// INVALID_LOG_RECORD_ID.
func newFscTransactionID() (string, error) {
	u, err := uuid.NewV7()
	if err != nil {
		return "", err
	}
	return u.String(), nil
}

// withFscTraceContext — middleware that runs BEFORE otelhttp and ties the
// FSC standard identifier (Fsc-Transaction-Id, UUID v7) to the OTel
// trace-id. Rationale: UUID v7 is 128 bits — exactly the format of an
// OTel trace-id — and FSC propagates it through the whole chain
// (including to the authz-service as X-Request-Id). By making our
// trace-id equal to this correlator, the adapter span, graphql span, and
// pdp span end up in the same Jaeger trace automatically, without
// patching FSC's context.Background() behavior in the AuthZen plugin.
//
// The middleware sets the Traceparent header on the incoming request;
// otelhttp reads it and uses it as the parent context for the root span.
// The UUID itself is stashed in the request context so callViaFSC can
// set it as the Fsc-Transaction-Id header on the outway call (same
// value, no second UUID). If the caller already sent a Traceparent
// (e.g. an issuance-server with OTel), we leave it alone — the flow
// then hangs off the existing trace and we only mint the FSC-tx-id for
// FSC propagation.
func withFscTraceContext(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fscTxID, err := newFscTransactionID()
		if err == nil {
			// If no traceparent is present, tie the trace-id to the UUID.
			if r.Header.Get("Traceparent") == "" {
				traceHex := strings.ReplaceAll(fscTxID, "-", "")
				spanHex := randomSpanIDHex()
				if len(traceHex) == 32 && spanHex != "" {
					r.Header.Set("Traceparent", "00-"+traceHex+"-"+spanHex+"-01")
				}
			}
			r = r.WithContext(context.WithValue(r.Context(), fscTxIDCtxKey, fscTxID))
		}
		next.ServeHTTP(w, r)
	})
}

// randomSpanIDHex returns 8 bytes of hex — a valid OTel span-id.
func randomSpanIDHex() string {
	var b [8]byte
	if _, err := rand.Read(b[:]); err != nil {
		return ""
	}
	return hex.EncodeToString(b[:])
}

// callViaFSC: POST to the real FSC-Outway on {OutwayURL}{uc.OutwayPath}.
// The Outway matches the path prefix against configured grant-links and
// resolves it to the grant-hash — no Fsc-Grant-Hash header needed; the
// adapter knows nothing about hashes or contract details.
//
// The Outway opens mTLS to the Inway (from the contract) and sets
// Fsc-Authorization: Bearer <token> itself. The Inway validates and
// forwards to the backend service. On DENY: 403 + reason.
//
// X-GBO-* headers pass through Outway/Inway transparently to the backend
// — untrusted but available.
func callViaFSC(ctx context.Context, client *http.Client, cfg config, bsn string, uc Usecase) ([]map[string]any, error) {
	if uc.OutwayPath == "" {
		return nil, fmt.Errorf("usecase %q has no outway_path in the catalog", uc.AttestationType)
	}

	bsnJSON, _ := json.Marshal(bsn)
	vars := map[string]any{"bsn": json.RawMessage(bsnJSON)}

	body, _ := json.Marshal(proxyRequest{
		Query:     buildQuery(uc),
		Variables: vars,
	})

	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, cfg.OutwayURL+uc.OutwayPath, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	httpReq.Header.Set("Content-Type", "application/json")
	// Context headers — untrusted, pass through the Outway/Inway.
	httpReq.Header.Set("X-GBO-Scope", uc.Scope)
	httpReq.Header.Set("X-GBO-Flow", "eudi:attestation")
	// Reuse the Fsc-Transaction-Id that the middleware already generated
	// and that also forms the trace-id. That way trace-id ==
	// Fsc-Transaction-Id — a single identifier across the whole chain
	// (adapter -> FSC txlog -> pdp span). If the context does not carry
	// it (e.g. this function is called directly without the middleware),
	// fall back to a fresh UUID.
	fscTxID, _ := ctx.Value(fscTxIDCtxKey).(string)
	if fscTxID == "" {
		gen, err := newFscTransactionID()
		if err != nil {
			return nil, fmt.Errorf("generate Fsc-Transaction-Id: %w", err)
		}
		fscTxID = gen
	}
	httpReq.Header.Set("Fsc-Transaction-Id", fscTxID)
	trace.SpanFromContext(ctx).SetAttributes(attribute.String("gbo.fsc.transaction_id", fscTxID))
	otel.GetTextMapPropagator().Inject(ctx, propagation.HeaderCarrier(httpReq.Header))

	resp, err := client.Do(httpReq)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	respBody, _ := io.ReadAll(resp.Body)

	if resp.StatusCode == http.StatusForbidden {
		var denied struct {
			Reason string `json:"reason"`
		}
		_ = json.Unmarshal(respBody, &denied)
		return nil, fmt.Errorf("denied by policy: %s", denied.Reason)
	}
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("fsc proxy status %d: %s", resp.StatusCode, string(respBody))
	}

	var out graphqlResponse
	if err := json.Unmarshal(respBody, &out); err != nil {
		return nil, fmt.Errorf("decode graphql response: %w", err)
	}
	if len(out.Errors) > 0 {
		return nil, fmt.Errorf("graphql errors: %v", out.Errors)
	}
	if out.Data.IngeschrevenPersoon == nil {
		return nil, nil
	}
	return out.Data.IngeschrevenPersoon.HeeftBelastingjaarAangifte, nil
}

// selectAangifte picks the aangifte for the usecase's tax year. The BD
// bron-schema has no year argument, so the bron returned all aangiften;
// the usecase's belastingjaren selects which one becomes the credential.
// Empty belastingjaren = first aangifte.
func selectAangifte(aangiften []map[string]any, jaren []int) map[string]any {
	if len(aangiften) == 0 {
		return nil
	}
	if len(jaren) == 0 {
		return aangiften[0]
	}
	for _, a := range aangiften {
		jaar, ok := a["belastingjaar"].(float64)
		if !ok {
			continue
		}
		for _, y := range jaren {
			if int(jaar) == y {
				return a
			}
		}
	}
	return nil
}

// formatAsIssuableDocuments converts the aangifte into the
// bri-mock-compatible shape that the nl-wallet-issuance-server expects:
//   - Flat array (no envelope)
//   - snake_case attributes; Bedrag objects ({waarde, valuta}) flattened
//     to eurocents (× 100) — bri convention
//   - Metadata (CA, issuer_uri, validity) is pulled by the issuance-server
//     itself from its config, so those fields are NOT included here.
//
// Attribute names match inkomensverklaring_metadata.json: belastingjaar,
// verzamelinkomen, inkomen_box1/2/3, status, indieningsdatum.
func formatAsIssuableDocuments(aangifte map[string]any, uc Usecase) []attestation {
	attrs := map[string]any{
		"belastingjaar":   aangifte["belastingjaar"],
		"verzamelinkomen": toCents(bedragWaarde(aangifte["verzamelinkomen"])),
	}
	if v, ok := aangifte["indieningsdatum"]; ok {
		attrs["indieningsdatum"] = v
	}
	if v, ok := aangifte["status"]; ok {
		attrs["status"] = v
	}
	if v := bedragWaarde(aangifte["box1Inkomen"]); v != nil {
		attrs["inkomen_box1"] = toCents(v)
	}
	if v := bedragWaarde(aangifte["box2Inkomen"]); v != nil {
		attrs["inkomen_box2"] = toCents(v)
	}
	if v := bedragWaarde(aangifte["box3Inkomen"]); v != nil {
		attrs["inkomen_box3"] = toCents(v)
	}
	attrs["verklaring_tekst"] = fmt.Sprintf("Inkomensverklaring %v via GBO/DvTP", attrs["belastingjaar"])

	return []attestation{{
		AttestationType: uc.AttestationType,
		Attributes:      attrs,
		Format:          "dc+sd-jwt",
		ID:              newUUIDv4(),
	}}
}

// bedragWaarde extracts the waarde from a Bedrag object ({waarde, valuta})
// as decoded from the GraphQL response. Returns nil when absent or not an
// object.
func bedragWaarde(v any) any {
	m, ok := v.(map[string]any)
	if !ok {
		return nil
	}
	return m["waarde"]
}

// newUUIDv4 generates an RFC4122 v4 UUID for the issuance-server's
// IssuableDocument.id (serde otherwise fails with "error decoding
// response body"). v4 (random) is fine here — the issuance-server only
// validates UUID format, not the version (unlike FSC, which requires v7
// — see newFscTransactionID).
func newUUIDv4() string {
	return uuid.NewString()
}

// toCents converts a JSON number into eurocents (× 100). GraphQL delivers
// float64; we multiply and round down.
func toCents(v any) int64 {
	switch n := v.(type) {
	case float64:
		return int64(n * 100)
	case int:
		return int64(n) * 100
	case int64:
		return n * 100
	}
	return 0
}

// safePrefix: only log the first 3 digits of a BSN — data minimization
// in transit.
func safePrefix(bsn string) string {
	if len(bsn) < 3 {
		return "***"
	}
	return bsn[:3] + "******"
}

func initTracer(ctx context.Context) (func(context.Context) error, error) {
	endpoint := getEnv("OTEL_EXPORTER_OTLP_ENDPOINT", "otel-collector:4317")
	serviceName := getEnv("OTEL_SERVICE_NAME", "eudi-adapter")
	exp, err := otlptracegrpc.New(ctx,
		otlptracegrpc.WithEndpoint(endpoint),
		otlptracegrpc.WithInsecure(),
	)
	if err != nil {
		return nil, err
	}
	res, err := resource.New(ctx, resource.WithAttributes(semconv.ServiceName(serviceName)))
	if err != nil {
		return nil, err
	}
	tp := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(exp, sdktrace.WithBatchTimeout(100*time.Millisecond)),
		sdktrace.WithResource(res),
	)
	otel.SetTracerProvider(tp)
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(
		propagation.TraceContext{},
		propagation.Baggage{},
	))
	return tp.Shutdown, nil
}

// newMux builds the routing tree with the given config, catalog and HTTP
// client. Extracted from main so integration tests can wire the handlers
// to an httptest.Server without starting the real listener.
func newMux(cfg config, catalog *Catalog, client *http.Client) *http.ServeMux {
	mux := http.NewServeMux()
	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"status":"ok"}`))
	})
	// One mux path per usecase; the issuance-server config points each
	// credential-configuration at /{usecase}/. The adapter selects scope
	// and query parameters from the catalog entry — no hard-coding.
	usecaseKeys := make([]string, 0, len(catalog.Usecases))
	for key, uc := range catalog.Usecases {
		usecaseKeys = append(usecaseKeys, key)
		// The issuance-server's base_url ends with '/' -> mux path idem.
		path := "/" + key + "/"
		mux.HandleFunc(path, handleAttestation(cfg, client, key, uc))
	}
	slog.Info("eudi-adapter usecases loaded", "keys", usecaseKeys)
	return mux
}

func main() {
	cfg := loadConfig()
	ctx := context.Background()
	shutdown, err := initTracer(ctx)
	if err != nil {
		slog.Error("tracer init failed", "err", err.Error())
		os.Exit(1)
	}
	defer func() { _ = shutdown(ctx) }()

	catalog, err := loadCatalog(cfg.CatalogPath)
	if err != nil {
		slog.Error("catalog load failed", "path", cfg.CatalogPath, "err", err.Error())
		os.Exit(1)
	}

	client := &http.Client{
		Timeout:   10 * time.Second,
		Transport: otelhttp.NewTransport(http.DefaultTransport),
	}

	mux := newMux(cfg, catalog, client)

	addr := ":" + cfg.Port
	slog.Info("eudi-adapter starting", "addr", addr, "outway", cfg.OutwayURL, "issuer_oin", cfg.IssuerOIN)
	// Middleware order: withFscTraceContext wraps otelhttp — the header
	// mutation must happen before otelhttp extracts the parent context.
	if err := http.ListenAndServe(addr, withFscTraceContext(otelhttp.NewHandler(mux, "eudi-adapter"))); err != nil {
		slog.Error("server stopped", "err", err.Error())
	}
}
