// Package main implements the EUDI adapter — a bridge between nl-wallet's
// issuance-server and the PEP/OpenFTV-PDP/graphql-server chain.
//
// Role:
//  1. Receives a POST from the issuance-server (contains disclosed PID with BSN)
//  2. POSTs to the FSC-Outway — no explicit token fetch, no Bearer. Outway
//     resolves the path prefix to a grant, opens mTLS to the target Inway,
//     and presents the token from the contract.
//  3. The Inway receives the request, validates the token, and forwards
//     to the backend service (PDP as AuthZen endpoint).
//  4. PEP dispatches on the flow (BSN comes from the disclosed PID; no
//     consent fetch, no BSNk transform).
//  5. On PDP ALLOW: the bron answers; the adapter formats
//     the response as an IssuableDocument list.
//
// Transport is uniform with the DvTP flow (both via FSC); the access basis
// still differs (PID vs consent). OIN authenticates the actor and the path,
// not the per-request authorization.
//
// Two bronprofielen are supported, selected per usecase via `bron` in the
// catalog:
//   - "bd"  — Belastingdienst; yields the inkomensverklaring attestation
//   - "brp" — Basisregistratie Personen; yields the akte van overlijden,
//     walking from the disclosing nabestaande to her huwelijkspartner
//
// DELIBERATELY OUT OF SCOPE for V1:
//   - PID signature verification (BSN is trusted)
//   - Wallet-cert check
//   - State between requests (each request is stateless)
//
// LOG HYGIENE: log the bare minimum. BSN prefix + attestation-type + trace-id.
// No data body. The adapter sits IN transit for sensitive data; full data
// minimization is a policy question left open.
package main

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/google/uuid"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
	"go.opentelemetry.io/otel/propagation"
	"go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.24.0"
	"go.opentelemetry.io/otel/trace"
)

// fscTxIDCtxKey stashes the Fsc-Transaction-Id generated by the middleware
// so callViaFSC can reuse it (instead of minting a second UUID).
type fscTxIDCtxKeyType struct{}

var fscTxIDCtxKey = fscTxIDCtxKeyType{}

// readHeaderTimeout bounds how long a client may take to send its request
// headers, so a stalled connection cannot hold a handler open.
const readHeaderTimeout = 10 * time.Second

type config struct {
	Port        string
	OutwayURL   string
	IssuerOIN   string
	CatalogPath string

	// Phase-1 pilot configuration for exactly one metadata source and one
	// attestation type. SourceMetadataShadowEnabled is the rollback flag:
	// false keeps the complete legacy path; true fetches and executes the
	// verified source query, still returns the legacy-formatted document, and
	// compares the source mapping against that document. In other words, only
	// the projection comparison is shadow traffic; the source query is active.
	//
	// These singular environment-backed fields are temporary. The onboarding
	// phase replaces them with the validated multi-source registry and cache.
	SourceMetadataShadowEnabled bool
	SourceMetadataOutwayPath    string
	SourceMetadataOIN           string
	SourceMetadataPublicJWKPath string
	SourceMetadataTypeID        string
	SourceMetadataUsecaseKey    string

	// Phase 3 keeps the phase-1 switch available for immediate rollback.
	// Enabling the cache activates refresh, immutable Type Metadata and
	// fail-closed expiry for the configured pilot type.
	SourceMetadataCacheEnabled bool
	TypeMetadataPublicBaseURL  string
	TypeMetadataStorePath      string
}

func loadConfig() config {
	return config{
		Port:        getEnv("PORT", "4009"),
		OutwayURL:   getEnv("FSC_OUTWAY_URL", "http://edi-outway:8080"),
		IssuerOIN:   getEnv("ISSUER_OIN", "00000004000000004000"),
		CatalogPath: getEnv("USECASE_CATALOG_PATH", "/config/usecase_catalog.json"),
		SourceMetadataShadowEnabled: strings.EqualFold(
			os.Getenv("SOURCE_METADATA_SHADOW_ENABLED"), "true",
		),
		SourceMetadataOutwayPath:    os.Getenv("SOURCE_METADATA_OUTWAY_PATH"),
		SourceMetadataOIN:           os.Getenv("SOURCE_METADATA_OIN"),
		SourceMetadataPublicJWKPath: os.Getenv("SOURCE_METADATA_PUBLIC_JWK_PATH"),
		SourceMetadataTypeID:        getEnv("SOURCE_METADATA_TYPE_ID", "inkomensverklaring"),
		SourceMetadataUsecaseKey:    getEnv("SOURCE_METADATA_USECASE_KEY", "inkomensverklaring_2025"),
		SourceMetadataCacheEnabled: strings.EqualFold(
			os.Getenv("SOURCE_METADATA_CACHE_ENABLED"), "true",
		),
		TypeMetadataPublicBaseURL: os.Getenv("TYPE_METADATA_PUBLIC_BASE_URL"),
		TypeMetadataStorePath:     getEnv("TYPE_METADATA_STORE_PATH", "/var/lib/gbo/type-metadata"),
	}
}

func getEnv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

// Usecase is a catalog entry — one per (attestation-type × parameter-set).
// The same attestation_type can have multiple entries (e.g. one per tax
// year); path-based routing (path-key = usecase-key) selects the active
// entry. The GraphQL query is built from the catalog; scope is forwarded
// as X-GBO-Scope to the PEP.
//
// OutwayPath is the FSC-Outway grant-link path for this source+service.
// Multiple usecases may share the same path as long as they consume the
// same FSC service — a single contract covers all of them (e.g. all three
// tax years via /bri/). A different source means a different path
// (e.g. /pid/ for RvIG).
type Usecase struct {
	AttestationType string `json:"attestation_type"`
	Scope           string `json:"scope"`
	Belastingjaren  []int  `json:"belastingjaren"`
	OutwayPath      string `json:"outway_path"`
	// Bron selects the bronprofiel: "bd" (Belastingdienst, default) or
	// "brp" (Basisregistratie Personen). It drives both the GraphQL query
	// that is built and how the response maps onto wallet attributes.
	Bron string `json:"bron,omitempty"`
	// Flow is sent as X-GBO-Flow and mirrors the `flow` additional claim
	// the provider's FSC Manager signs into the token. The PDP uses it to
	// pick the mirror schema, so it has to name the bronprofiel too.
	// Defaults to the BD flow.
	Flow string `json:"flow,omitempty"`
	Note string `json:"note,omitempty"`
}

// Bronprofielen the adapter can read.
const (
	bronBD  = "bd"
	bronBRP = "brp"
)

// Flows, matching pdp-service's flowSchemaFiles keys.
const (
	flowEudiBD  = "eudi:attestation"
	flowEudiBRP = "eudi:attestation:brp"
)

// bron returns the usecase's bronprofiel, defaulting to BD so existing
// catalog entries keep working unchanged.
func (u Usecase) bron() string {
	if u.Bron == "" {
		return bronBD
	}
	return u.Bron
}

// flow returns the usecase's flow, defaulting to the flow that matches its
// bronprofiel. An explicit `flow` in the catalog wins, so a deployment can
// point a usecase at a different policy path without a code change.
func (u Usecase) flow() string {
	if u.Flow != "" {
		return u.Flow
	}
	if u.bron() == bronBRP {
		return flowEudiBRP
	}
	return flowEudiBD
}

type Catalog struct {
	Usecases map[string]Usecase `json:"usecases"`
}

func loadCatalog(path string) (*Catalog, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read catalog: %w", err)
	}
	var c Catalog
	if err := json.Unmarshal(data, &c); err != nil {
		return nil, fmt.Errorf("parse catalog: %w", err)
	}
	if len(c.Usecases) == 0 {
		return nil, fmt.Errorf("catalog has no usecases")
	}
	return &c, nil
}

// overlijdenPartnerQuery is the akte-van-overlijden query against the BRP
// bron-schema. It is rooted at the disclosing nabestaande's own BSN and
// reaches the overledene only through the marriage she is a party to —
// that path IS the authorization argument, and rule EUD0002 mirrors it in
// covers_fields.
//
// `partners` is symmetric (both spouses are listed), so the adapter picks
// the one with a datumOverlijden; see selectOverledenPartner.
const overlijdenPartnerQuery = `query OverlijdenPartner($bsn: BSN!) {
  ingeschrevenPersoon(bsn: $bsn) {
    id
    bsn
    geslachtsnaam
    voorvoegsel
    voornamen
    heeftHuwelijk {
      soortVerbintenis
      datumVoltrekking
      plaatsVoltrekking
      landVoltrekking
      datumOntbinding
      redenOntbinding
      partners {
        id
        geslachtsnaam
        voorvoegsel
        voornamen
        geboortedatum
        geboorteplaats
        geboorteland
        geslacht
        datumOverlijden
        plaatsOverlijden
        landOverlijden
        heeftOuder {
          geslachtsnaam
          voorvoegsel
          voornamen
        }
      }
    }
  }
}`

// buildQuery builds the GraphQL query for the usecase's bronprofiel.
//
// BD: the usecase's belastingjaren are embedded as the year filter so the
// PDP can enforce per-year authorization (rule EUD0001's years_in_scopes
// check); the bron returns exactly those years.
// BRP: a fixed query — the akte has no parameter beyond the BSN.
func buildQuery(u Usecase) string {
	if u.bron() == bronBRP {
		return overlijdenPartnerQuery
	}
	jaren, _ := json.Marshal(u.Belastingjaren) // -> "[2024]" etc.
	return fmt.Sprintf(`query($bsn: BSN!) {
  ingeschrevenPersoon(bsn: $bsn) {
    heeftBelastingjaarAangifte(belastingjaren: %s) {
      belastingjaar status indieningsdatum
      ... on AangifteIH {
        verzamelinkomen { waarde valuta }
        box1Inkomen { waarde valuta }
        box2Inkomen { waarde valuta }
        box3Inkomen { waarde valuta }
      }
    }
  }
}`, string(jaren))
}

// issuanceServerRequest — a real disclosure can carry the BSN in two
// places (reverse-engineered from bri-mock.rs::extract_bsn):
//   - `attributes.urn:eudi:pid:nl:1.bsn` (nested, real PID sd-jwt)
//   - `attributes.bsn` (flat, test shape)
//
// We decode as `map[string]any` so both shapes can be scanned.
type issuanceServerRequest []struct {
	Attestations []struct {
		AttestationType string         `json:"attestation_type"`
		Attributes      map[string]any `json:"attributes"`
	} `json:"attestations"`
	ID string `json:"id"`
}

// extractBSN scans the attributes map for a BSN. It follows the same
// pattern as bri-mock.rs::extract_bsn: first nested under the PID
// namespace, then flat.
func extractBSN(attrs map[string]any) string {
	if nested, ok := attrs["urn:eudi:pid:nl:1"].(map[string]any); ok {
		if s, ok := nested["bsn"].(string); ok {
			return s
		}
	}
	if s, ok := attrs["bsn"].(string); ok {
		return s
	}
	// Fallback: any one-level-deeper map with "bsn".
	for _, v := range attrs {
		if m, ok := v.(map[string]any); ok {
			if s, ok := m["bsn"].(string); ok {
				return s
			}
		}
	}
	return ""
}

// attestation matches 1:1 the shape returned by bri-mock (reverse-
// engineered via curl). The issuance-server expects a flat array — no
// envelope; metadata (CA, issuer_uri, validity) is pulled by the
// issuance-server itself from its own config.
type attestation struct {
	AttestationType string         `json:"attestation_type"`
	Attributes      map[string]any `json:"attributes"`
	Format          string         `json:"format"`
	ID              string         `json:"id"`
}

// proxyRequest is the pure GraphQL body that the FSC-Inway forwards 1:1
// to the PEP's /evaluate endpoint. All context lives in HTTP headers:
//   - Authorization: Bearer <FSC-token>   -> Inway validates + propagates
//   - X-GBO-Scope: bd:ib:2025              -> PDP hint (untrusted)
//   - X-GBO-Flow: eudi:attestation         -> PEP dispatch (untrusted)
//
// BSN is already in the query variables (`$bsn`); no separate body field.
type proxyRequest struct {
	Query     string         `json:"query"`
	Variables map[string]any `json:"variables,omitempty"`
}

// graphqlResponse: on ALLOW the PEP forwards the bron's body 1:1. Both
// bronprofielen root their answer at `ingeschrevenPersoon`, but the shape
// underneath differs per bronprofiel, so it stays raw here and is decoded
// by the per-bron path in buildIssuableDocuments.
type graphqlResponse struct {
	Data struct {
		IngeschrevenPersoon json.RawMessage `json:"ingeschrevenPersoon"`
	} `json:"data"`
	Errors []map[string]any `json:"errors,omitempty"`
}

type sourceQueryPlan struct {
	Query     string
	Variables map[string]any
}

type fscResult struct {
	Persoon json.RawMessage
	Raw     []byte
}

// errNoData signals "the bron knows this person but not the facts this
// usecase needs" — a 404 for the issuance-server, not a failure.
var errNoData = fmt.Errorf("no data")

// handleAttestation is the per-usecase handler that the issuance-server
// calls via attestation_url_config.base_url. The usecase key comes from
// the mux registration (per path); all parameters (scope, tax year,
// attestation-type) come from the catalog entry — nothing is hard-coded
// in the adapter code.
func handleAttestation(cfg config, client *http.Client, usecaseKey string, uc Usecase, metadataRuntime sourceMetadataRuntime) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		// The catalog decides which bron this usecase reads from; put that on
		// the span so a trace-reader (dev-portal architecture-strip) can name
		// the register without a second usecase → bron table of its own. Set
		// before any work: a run that never reaches the bron (policy DENY,
		// unknown BSN) still says which register it would have queried.
		trace.SpanFromContext(r.Context()).SetAttributes(
			attribute.String("gbo.bron", uc.bron()),
			attribute.String("gbo.usecase", usecaseKey),
		)
		body, err := io.ReadAll(io.LimitReader(r.Body, 4<<20))
		if err != nil {
			http.Error(w, "read body: "+err.Error(), http.StatusBadRequest)
			return
		}

		var req issuanceServerRequest
		if err := json.Unmarshal(body, &req); err != nil {
			slog.Error("parse issuance-server request", "err", err.Error(), "raw_len", len(body))
			http.Error(w, "invalid request", http.StatusBadRequest)
			return
		}
		if len(req) == 0 || len(req[0].Attestations) == 0 {
			slog.Error("no attestation in disclosure", "body_len", len(body))
			http.Error(w, "no PID attestation in disclosure", http.StatusBadRequest)
			return
		}

		// V1: take the first PID attestation. The BSN is trusted.
		bsn := extractBSN(req[0].Attestations[0].Attributes)
		if bsn == "" {
			attrKeys := make([]string, 0, len(req[0].Attestations[0].Attributes))
			for k := range req[0].Attestations[0].Attributes {
				attrKeys = append(attrKeys, k)
			}
			slog.Error("no BSN in disclosed PID", "usecase", usecaseKey, "attr_keys", attrKeys)
			http.Error(w, "no BSN in disclosed PID", http.StatusBadRequest)
			return
		}
		slog.Info("adapter received disclosure",
			"usecase", usecaseKey,
			"bsn_present", true,
			"attestation_type", uc.AttestationType,
			"bron", uc.bron(),
			"flow", uc.flow(),
			"scope", uc.Scope,
			"belastingjaren", uc.Belastingjaren,
		)

		// Policy check + data fetch via FSC -> PEP -> PDP -> OPA -> bron.
		// In shadow mode the verified source definition supplies the query;
		// otherwise the existing catalog-driven query remains the fallback.
		var shadow *sourceMetadataShadow
		if metadataRuntime != nil && metadataRuntime.appliesTo(usecaseKey, uc) {
			shadow, err = metadataRuntime.current(time.Now())
			if err != nil {
				slog.Error("source metadata unavailable", "usecase", usecaseKey, "err", err.Error())
				http.Error(w, "source metadata unavailable", http.StatusServiceUnavailable)
				return
			}
			if shadow.CacheState != "" {
				w.Header().Set("X-GBO-Metadata-Cache", shadow.CacheState)
			}
		}
		var queryPlans []sourceQueryPlan
		if shadow != nil {
			plan, err := shadow.queryPlan(usecaseKey, bsn, uc)
			if err != nil {
				slog.Error("build source metadata query", "usecase", usecaseKey, "err", err.Error())
				http.Error(w, err.Error(), http.StatusBadGateway)
				return
			}
			queryPlans = append(queryPlans, plan)
		}
		result, err := callViaFSC(r.Context(), client, cfg, bsn, uc, queryPlans...)
		if err != nil {
			slog.Error("fsc call failed", "usecase", usecaseKey, "err", err.Error())
			http.Error(w, err.Error(), http.StatusBadGateway)
			return
		}

		docs, err := buildIssuableDocuments(uc, result.Persoon)
		if err != nil {
			if errors.Is(err, errNoData) {
				slog.Info("bron has no data for this usecase", "usecase", usecaseKey, "bron", uc.bron())
				http.Error(w, noDataMessage(uc), http.StatusNotFound)
				return
			}
			slog.Error("format attestation failed", "usecase", usecaseKey, "err", err.Error())
			http.Error(w, err.Error(), http.StatusBadGateway)
			return
		}
		if shadow != nil {
			matches, compareErr := shadow.compareLegacy(result.Raw, docs)
			switch {
			case compareErr != nil:
				w.Header().Set("X-GBO-Metadata-Shadow", "error")
				slog.Error("source metadata shadow comparison failed", "usecase", usecaseKey, "err", compareErr.Error())
			case !matches:
				w.Header().Set("X-GBO-Metadata-Shadow", "mismatch")
				slog.Warn("source metadata shadow mismatch", "usecase", usecaseKey, "metadata_version", shadow.Version)
			default:
				w.Header().Set("X-GBO-Metadata-Shadow", "match")
			}
			if shadow.VCT != "" && shadow.VCTIntegrity != "" {
				for i := range docs {
					docs[i].AttestationType = shadow.VCT
					docs[i].Attributes["vct#integrity"] = shadow.VCTIntegrity
				}
			}
		}

		w.Header().Set("Content-Type", "application/json")
		if err := json.NewEncoder(w).Encode(docs); err != nil {
			slog.Error("encode response", "err", err.Error())
		}
	}
}

// newFscTransactionID returns a UUID **v7** (time-ordered) — the
// FSC-Outway explicitly validates v7 and rejects v4 with
// INVALID_LOG_RECORD_ID.
func newFscTransactionID() (string, error) {
	u, err := uuid.NewV7()
	if err != nil {
		return "", err
	}
	return u.String(), nil
}

// withFscTraceContext — middleware that runs BEFORE otelhttp and ties the
// FSC standard identifier (Fsc-Transaction-Id, UUID v7) to the OTel
// trace-id. Rationale: UUID v7 is 128 bits — exactly the format of an
// OTel trace-id — and FSC propagates it through the whole chain
// (including to the authz-service as X-Request-Id). By making our
// trace-id equal to this correlator, the adapter span, graphql span, and
// pdp span end up in the same Jaeger trace automatically, without
// patching FSC's context.Background() behavior in the AuthZen plugin.
//
// The middleware sets the Traceparent header on the incoming request;
// otelhttp reads it and uses it as the parent context for the root span.
// The UUID itself is stashed in the request context so callViaFSC can
// set it as the Fsc-Transaction-Id header on the outway call (same
// value, no second UUID). If the caller already sent a Traceparent
// (e.g. an issuance-server with OTel), we leave it alone — the flow
// then hangs off the existing trace and we only mint the FSC-tx-id for
// FSC propagation.
func withFscTraceContext(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fscTxID, err := newFscTransactionID()
		if err == nil {
			// If no traceparent is present, tie the trace-id to the UUID.
			if r.Header.Get("Traceparent") == "" {
				traceHex := strings.ReplaceAll(fscTxID, "-", "")
				spanHex := randomSpanIDHex()
				if len(traceHex) == 32 && spanHex != "" {
					r.Header.Set("Traceparent", "00-"+traceHex+"-"+spanHex+"-01")
				}
			}
			r = r.WithContext(context.WithValue(r.Context(), fscTxIDCtxKey, fscTxID))
		}
		next.ServeHTTP(w, r)
	})
}

// randomSpanIDHex returns 8 bytes of hex — a valid OTel span-id.
func randomSpanIDHex() string {
	var b [8]byte
	if _, err := rand.Read(b[:]); err != nil {
		return ""
	}
	return hex.EncodeToString(b[:])
}

// callViaFSC: POST to the real FSC-Outway on {OutwayURL}{uc.OutwayPath}.
// The Outway matches the path prefix against configured grant-links and
// resolves it to the grant-hash — no Fsc-Grant-Hash header needed; the
// adapter knows nothing about hashes or contract details.
//
// The Outway opens mTLS to the Inway (from the contract) and sets
// Fsc-Authorization: Bearer <token> itself. The Inway validates and
// forwards to the backend service. On DENY: 403 + reason.
//
// X-GBO-* headers pass through Outway/Inway transparently to the backend
// — untrusted but available.
//
// Returns both the raw GraphQL body for generic projection and the extracted
// `ingeschrevenPersoon` object for the legacy formatter.
func callViaFSC(ctx context.Context, client *http.Client, cfg config, bsn string, uc Usecase, plans ...sourceQueryPlan) (fscResult, error) {
	if uc.OutwayPath == "" {
		return fscResult{}, fmt.Errorf("usecase %q has no outway_path in the catalog", uc.AttestationType)
	}

	query := buildQuery(uc)
	vars := map[string]any{"bsn": bsn}
	if len(plans) > 1 {
		return fscResult{}, fmt.Errorf("only one source query plan can be active")
	}
	if len(plans) == 1 {
		query = plans[0].Query
		vars = plans[0].Variables
	}

	body, _ := json.Marshal(proxyRequest{
		Query:     query,
		Variables: vars,
	})

	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, cfg.OutwayURL+uc.OutwayPath, bytes.NewReader(body))
	if err != nil {
		return fscResult{}, err
	}
	httpReq.Header.Set("Content-Type", "application/json")
	// Context headers — untrusted, pass through the Outway/Inway.
	httpReq.Header.Set("X-GBO-Scope", uc.Scope)
	httpReq.Header.Set("X-GBO-Flow", uc.flow())
	// Reuse the Fsc-Transaction-Id that the middleware already generated
	// and that also forms the trace-id. That way trace-id ==
	// Fsc-Transaction-Id — a single identifier across the whole chain
	// (adapter -> FSC txlog -> pdp span). If the context does not carry
	// it (e.g. this function is called directly without the middleware),
	// fall back to a fresh UUID.
	fscTxID, _ := ctx.Value(fscTxIDCtxKey).(string)
	if fscTxID == "" {
		gen, err := newFscTransactionID()
		if err != nil {
			return fscResult{}, fmt.Errorf("generate Fsc-Transaction-Id: %w", err)
		}
		fscTxID = gen
	}
	httpReq.Header.Set("Fsc-Transaction-Id", fscTxID)
	trace.SpanFromContext(ctx).SetAttributes(attribute.String("gbo.fsc.transaction_id", fscTxID))
	otel.GetTextMapPropagator().Inject(ctx, propagation.HeaderCarrier(httpReq.Header))

	resp, err := client.Do(httpReq)
	if err != nil {
		return fscResult{}, err
	}
	defer resp.Body.Close()
	respBody, _ := io.ReadAll(resp.Body)

	if resp.StatusCode == http.StatusForbidden {
		var denied struct {
			Reason string `json:"reason"`
		}
		_ = json.Unmarshal(respBody, &denied)
		return fscResult{}, fmt.Errorf("denied by policy: %s", denied.Reason)
	}
	if resp.StatusCode != http.StatusOK {
		return fscResult{}, fmt.Errorf("fsc proxy status %d: %s", resp.StatusCode, string(respBody))
	}

	var out graphqlResponse
	if err := json.Unmarshal(respBody, &out); err != nil {
		return fscResult{}, fmt.Errorf("decode graphql response: %w", err)
	}
	if len(out.Errors) > 0 {
		return fscResult{}, fmt.Errorf("graphql errors: %v", out.Errors)
	}
	return fscResult{Persoon: out.Data.IngeschrevenPersoon, Raw: respBody}, nil
}

// buildIssuableDocuments turns the bron's `ingeschrevenPersoon` object into
// the issuance-server's IssuableDocument list, dispatching on the usecase's
// bronprofiel. Returns errNoData when the person exists but not the facts
// this usecase needs (the caller answers 404).
func buildIssuableDocuments(uc Usecase, persoon json.RawMessage) ([]attestation, error) {
	if len(persoon) == 0 || string(persoon) == "null" {
		return nil, errNoData
	}
	if uc.bron() == bronBRP {
		var p brpPersoon
		if err := json.Unmarshal(persoon, &p); err != nil {
			return nil, fmt.Errorf("decode brp persoon: %w", err)
		}
		huwelijk, overledene, ok := selectOverledenPartner(p)
		if !ok {
			return nil, errNoData
		}
		return formatAkteVanOverlijden(p, huwelijk, overledene, uc), nil
	}

	var p struct {
		HeeftBelastingjaarAangifte []map[string]any `json:"heeftBelastingjaarAangifte"`
	}
	if err := json.Unmarshal(persoon, &p); err != nil {
		return nil, fmt.Errorf("decode bd persoon: %w", err)
	}
	aangifte := selectAangifte(p.HeeftBelastingjaarAangifte, uc.Belastingjaren)
	if aangifte == nil {
		return nil, errNoData
	}
	return formatAsIssuableDocuments(aangifte, uc), nil
}

// noDataMessage keeps the 404 body specific per bronprofiel — during a live
// demo the difference between "wrong BSN" and "this person has no deceased
// partner" is the whole point.
func noDataMessage(uc Usecase) string {
	if uc.bron() == bronBRP {
		return "no huwelijk with an overleden partner found for this BSN"
	}
	return "no aangifte found for BSN and belastingjaar"
}

// selectAangifte picks the aangifte for the usecase's tax year. The query
// already filters by year at the bron; this is defense-in-depth in case a
// bron ignores the filter. Empty belastingjaren = first aangifte.
func selectAangifte(aangiften []map[string]any, jaren []int) map[string]any {
	if len(aangiften) == 0 {
		return nil
	}
	if len(jaren) == 0 {
		return aangiften[0]
	}
	for _, a := range aangiften {
		jaar, ok := a["belastingjaar"].(float64)
		if !ok {
			continue
		}
		for _, y := range jaren {
			if int(jaar) == y {
				return a
			}
		}
	}
	return nil
}

// formatAsIssuableDocuments converts the aangifte into the
// bri-mock-compatible shape that the nl-wallet-issuance-server expects:
//   - Flat array (no envelope)
//   - snake_case attributes; Bedrag objects ({waarde, valuta}) flattened
//     to whole euros — readable in the wallet UI
//   - Metadata (CA, issuer_uri, validity) is pulled by the issuance-server
//     itself from its config, so those fields are NOT included here.
//
// Attribute names match inkomensverklaring_metadata.json: belastingjaar,
// verzamelinkomen, inkomen_box1/2/3, status, indieningsdatum.
func formatAsIssuableDocuments(aangifte map[string]any, uc Usecase) []attestation {
	attrs := map[string]any{
		"belastingjaar":   aangifte["belastingjaar"],
		"verzamelinkomen": toEuros(bedragWaarde(aangifte["verzamelinkomen"])),
	}
	if v, ok := aangifte["indieningsdatum"]; ok {
		attrs["indieningsdatum"] = v
	}
	if v, ok := aangifte["status"]; ok {
		attrs["aangifte_status"] = v
	}
	if v := bedragWaarde(aangifte["box1Inkomen"]); v != nil {
		attrs["inkomen_box1"] = toEuros(v)
	}
	if v := bedragWaarde(aangifte["box2Inkomen"]); v != nil {
		attrs["inkomen_box2"] = toEuros(v)
	}
	if v := bedragWaarde(aangifte["box3Inkomen"]); v != nil {
		attrs["inkomen_box3"] = toEuros(v)
	}
	attrs["verklaring_tekst"] = fmt.Sprintf("Inkomensverklaring %v als GBO PubEAA", attrs["belastingjaar"])

	return []attestation{{
		AttestationType: uc.AttestationType,
		Attributes:      attrs,
		Format:          "dc+sd-jwt",
		ID:              newUUIDv4(),
	}}
}

// ── BRP: akte van overlijden ─────────────────────────────────────────────────

// The BRP response shapes, limited to what overlijdenPartnerQuery asks for.
// Optional fields are plain strings: the bron returns null for "unknown",
// which decodes to "" here, and empty values are simply omitted from the
// attestation rather than issued as an empty claim.

type brpOuder struct {
	Geslachtsnaam string `json:"geslachtsnaam"`
	Voorvoegsel   string `json:"voorvoegsel"`
	Voornamen     string `json:"voornamen"`
}

type brpPartner struct {
	ID               string     `json:"id"`
	Geslachtsnaam    string     `json:"geslachtsnaam"`
	Voorvoegsel      string     `json:"voorvoegsel"`
	Voornamen        string     `json:"voornamen"`
	Geboortedatum    string     `json:"geboortedatum"`
	Geboorteplaats   string     `json:"geboorteplaats"`
	Geboorteland     string     `json:"geboorteland"`
	Geslacht         string     `json:"geslacht"`
	DatumOverlijden  string     `json:"datumOverlijden"`
	PlaatsOverlijden string     `json:"plaatsOverlijden"`
	LandOverlijden   string     `json:"landOverlijden"`
	HeeftOuder       []brpOuder `json:"heeftOuder"`
}

type brpHuwelijk struct {
	SoortVerbintenis  string       `json:"soortVerbintenis"`
	DatumVoltrekking  string       `json:"datumVoltrekking"`
	PlaatsVoltrekking string       `json:"plaatsVoltrekking"`
	LandVoltrekking   string       `json:"landVoltrekking"`
	DatumOntbinding   string       `json:"datumOntbinding"`
	RedenOntbinding   string       `json:"redenOntbinding"`
	Partners          []brpPartner `json:"partners"`
}

type brpPersoon struct {
	ID            string        `json:"id"`
	BSN           string        `json:"bsn"`
	Geslachtsnaam string        `json:"geslachtsnaam"`
	Voorvoegsel   string        `json:"voorvoegsel"`
	Voornamen     string        `json:"voornamen"`
	HeeftHuwelijk []brpHuwelijk `json:"heeftHuwelijk"`
}

// datumVolledig reports whether a BRP DatumIncompleet carries a full calendar
// date. The scalar also permits partials ("2026", "2026-02"), which cannot be
// compared day-for-day.
func datumVolledig(d string) bool {
	_, err := time.Parse("2006-01-02", d)
	return err == nil
}

// selectOverledenPartner finds the marriage that was ended by the death of the
// requester's partner, across all of the requester's marriages.
//
// `partners` is symmetric per the BRP bronprofiel — both spouses are in the
// list — so the requester herself is filtered out by id, and what remains is
// a partner with a datumOverlijden.
//
// A datumOverlijden alone is not enough to certify: an ex-partner from a
// marriage dissolved by echtscheiding also dies eventually, and the BRP keeps
// that marriage on the persoonslijst. The nabestaande of that death is whoever
// the deceased was married to at the time, not the earlier ex-spouse. So the
// verbintenis itself must say it ended in this death:
//   - redenOntbinding is "Overlijden", and
//   - where both DatumIncompleet values are full dates, the ontbinding falls
//     on the day of the overlijden.
//
// A person can be widowed more than once; the most recent overlijden wins
// (ISO dates sort lexically, and a partial DatumIncompleet like "2026" still
// sorts before "2026-02-14", which is the conservative order here).
func selectOverledenPartner(p brpPersoon) (brpHuwelijk, brpPartner, bool) {
	var bestH brpHuwelijk
	var bestP brpPartner
	found := false
	for _, h := range p.HeeftHuwelijk {
		if h.RedenOntbinding != "Overlijden" {
			continue
		}
		for _, partner := range h.Partners {
			if partner.DatumOverlijden == "" {
				continue
			}
			// Guard against a bron that lists the requester herself as
			// overleden (she is disclosing a PID, so she is not).
			if partner.ID != "" && partner.ID == p.ID {
				continue
			}
			// Both dates complete → they must be the same day: the ontbinding
			// IS this overlijden. Partials are let through; refusing them
			// would deny an akte over a bron's date precision.
			if datumVolledig(h.DatumOntbinding) && datumVolledig(partner.DatumOverlijden) &&
				h.DatumOntbinding != partner.DatumOverlijden {
				continue
			}
			if !found || partner.DatumOverlijden > bestP.DatumOverlijden {
				bestH, bestP, found = h, partner, true
			}
		}
	}
	return bestH, bestP, found
}

// volledigeNaam renders voornamen + voorvoegsel + geslachtsnaam as one
// readable string, skipping the parts the BRP does not have.
func volledigeNaam(voornamen, voorvoegsel, geslachtsnaam string) string {
	parts := make([]string, 0, 3)
	for _, s := range []string{voornamen, voorvoegsel, geslachtsnaam} {
		if s != "" {
			parts = append(parts, s)
		}
	}
	return strings.Join(parts, " ")
}

// verbintenisOmschrijving renders the relationship the way an akte words it.
// Deliberately not gendered ("gehuwd met" instead of echtgenoot/echtgenote),
// because the BRP geslacht of the surviving partner is not queried.
func verbintenisOmschrijving(soort string) string {
	if soort == "GeregistreerdPartnerschap" {
		return "geregistreerd partner van"
	}
	return "gehuwd met"
}

// akteVerklaring renders the declaratory sentence of the akte, in the order
// the ambtenaar van de burgerlijke stand writes it: date and place of death,
// the deceased, birth date and place, and the surviving spouse.
func akteVerklaring(persoon brpPersoon, huwelijk brpHuwelijk, overledene brpPartner) string {
	overledeneNaam := volledigeNaam(overledene.Voornamen, overledene.Voorvoegsel, overledene.Geslachtsnaam)
	echtgenootNaam := volledigeNaam(persoon.Voornamen, persoon.Voorvoegsel, persoon.Geslachtsnaam)

	zin := fmt.Sprintf("Op %s is", overledene.DatumOverlijden)
	if overledene.PlaatsOverlijden != "" {
		zin += fmt.Sprintf(" te %s", overledene.PlaatsOverlijden)
	}
	zin += fmt.Sprintf(" overleden %s", overledeneNaam)
	if overledene.Geboortedatum != "" {
		zin += fmt.Sprintf(", geboren op %s", overledene.Geboortedatum)
		if overledene.Geboorteplaats != "" {
			zin += fmt.Sprintf(" te %s", overledene.Geboorteplaats)
		}
	}
	if echtgenootNaam != "" {
		zin += fmt.Sprintf(", %s %s", verbintenisOmschrijving(huwelijk.SoortVerbintenis), echtgenootNaam)
	}
	return zin + "."
}

// formatAkteVanOverlijden maps the BRP answer onto the akte's wallet
// attributes. Same conventions as the BD path: a flat array, snake_case
// attribute names matching akte_van_overlijden_metadata.json, and no
// metadata fields (the issuance-server adds those from its own config).
//
// The attributes are the ones a Dutch akte van overlijden carries: who died,
// when and where, born when and where, the parents, and — if applicable — the
// echtgenoot or geregistreerd partner. The query asks for more than that on
// purpose:
//   - datumOntbinding / redenOntbinding / datumVoltrekking / plaatsVoltrekking
//     / landVoltrekking establish WHICH marriage and that it ended in death.
//     They belong on the huwelijksakte, not on this one, so they are used to
//     select and then dropped.
//   - bsn and the ids identify the persoonslijst; an akte carries neither.
//
// Conversely, three things a paper akte does carry are absent because the BRP
// bronprofiel does not offer them: the gemeente van opmaak + aktenummer, the
// aangever, and the tijdstip (uur) van overlijden. The laatste woonplaats
// would be reachable via `woontOp`, but that is deliberately outside
// EUD0002's covers_fields — it is address data, not overlijdensdata.
//
// Empty source values are omitted rather than issued as empty claims — an
// akte should not assert "plaats van overlijden: <leeg>".
func formatAkteVanOverlijden(persoon brpPersoon, huwelijk brpHuwelijk, overledene brpPartner, uc Usecase) []attestation {
	attrs := map[string]any{
		"overledene_geslachtsnaam": overledene.Geslachtsnaam,
		"datum_overlijden":         overledene.DatumOverlijden,
		// The akte words the relationship as "echtgenoot of geregistreerd
		// partner"; soort_verbintenis disambiguates the two.
		"soort_verbintenis":        huwelijk.SoortVerbintenis,
		"echtgenoot_geslachtsnaam": persoon.Geslachtsnaam,
	}
	optional := map[string]string{
		"overledene_voorvoegsel":    overledene.Voorvoegsel,
		"overledene_voornamen":      overledene.Voornamen,
		"overledene_geboortedatum":  overledene.Geboortedatum,
		"overledene_geboorteplaats": overledene.Geboorteplaats,
		"overledene_geboorteland":   overledene.Geboorteland,
		"overledene_geslacht":       overledene.Geslacht,
		"plaats_overlijden":         overledene.PlaatsOverlijden,
		"land_overlijden":           overledene.LandOverlijden,
		"echtgenoot_voorvoegsel":    persoon.Voorvoegsel,
		"echtgenoot_voornamen":      persoon.Voornamen,
	}
	for k, v := range optional {
		if v != "" {
			attrs[k] = v
		}
	}

	// The ouders of the overledene are on a paper akte too. SD-JWT claims
	// are flat here, so they are rendered as one display string instead of
	// a nested array.
	ouders := make([]string, 0, len(overledene.HeeftOuder))
	for _, o := range overledene.HeeftOuder {
		if naam := volledigeNaam(o.Voornamen, o.Voorvoegsel, o.Geslachtsnaam); naam != "" {
			ouders = append(ouders, naam)
		}
	}
	if len(ouders) > 0 {
		attrs["overledene_ouders"] = strings.Join(ouders, "; ")
	}

	attrs["verklaring_tekst"] = akteVerklaring(persoon, huwelijk, overledene)

	return []attestation{{
		AttestationType: uc.AttestationType,
		Attributes:      attrs,
		Format:          "dc+sd-jwt",
		ID:              newUUIDv4(),
	}}
}

// bedragWaarde extracts the waarde from a Bedrag object ({waarde, valuta})
// as decoded from the GraphQL response. Returns nil when absent or not an
// object.
func bedragWaarde(v any) any {
	m, ok := v.(map[string]any)
	if !ok {
		return nil
	}
	return m["waarde"]
}

// newUUIDv4 generates an RFC4122 v4 UUID for the issuance-server's
// IssuableDocument.id (serde otherwise fails with "error decoding
// response body"). v4 (random) is fine here — the issuance-server only
// validates UUID format, not the version (unlike FSC, which requires v7
// — see newFscTransactionID).
func newUUIDv4() string {
	return uuid.NewString()
}

// toEuros converts a JSON number into whole euros. GraphQL delivers
// float64; we truncate to an integer.
func toEuros(v any) int64 {
	switch n := v.(type) {
	case float64:
		return int64(n)
	case int:
		return int64(n)
	case int64:
		return n
	}
	return 0
}

func initTracer(ctx context.Context) (func(context.Context) error, error) {
	endpoint := getEnv("OTEL_EXPORTER_OTLP_ENDPOINT", "otel-collector:4317")
	serviceName := getEnv("OTEL_SERVICE_NAME", "eudi-adapter")
	exp, err := otlptracegrpc.New(ctx,
		otlptracegrpc.WithEndpoint(endpoint),
		otlptracegrpc.WithInsecure(),
	)
	if err != nil {
		return nil, err
	}
	res, err := resource.New(ctx, resource.WithAttributes(semconv.ServiceName(serviceName)))
	if err != nil {
		return nil, err
	}
	tp := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(exp, sdktrace.WithBatchTimeout(100*time.Millisecond)),
		sdktrace.WithResource(res),
	)
	otel.SetTracerProvider(tp)
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(
		propagation.TraceContext{},
		propagation.Baggage{},
	))
	return tp.Shutdown, nil
}

// newMux builds the routing tree with the given config, catalog and HTTP
// client. Extracted from main so integration tests can wire the handlers
// to an httptest.Server without starting the real listener.
func newMux(cfg config, catalog *Catalog, client *http.Client, runtimes ...sourceMetadataRuntime) *http.ServeMux {
	var metadataRuntime sourceMetadataRuntime
	if len(runtimes) > 0 {
		metadataRuntime = runtimes[0]
	}
	mux := http.NewServeMux()
	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"status":"ok"}`))
	})
	// One mux path per usecase; the issuance-server config points each
	// credential-configuration at /{usecase}/. The adapter selects scope
	// and query parameters from the catalog entry — no hard-coding.
	usecaseKeys := make([]string, 0, len(catalog.Usecases))
	for key, uc := range catalog.Usecases {
		usecaseKeys = append(usecaseKeys, key)
		// The issuance-server's base_url ends with '/' -> mux path idem.
		path := "/" + key + "/"
		mux.HandleFunc(path, handleAttestation(cfg, client, key, uc, metadataRuntime))
	}
	if publisher, ok := metadataRuntime.(http.Handler); ok {
		mux.Handle("/types/", publisher)
	}
	slog.Info("eudi-adapter usecases loaded", "keys", usecaseKeys)
	return mux
}

// newRuntimeMux activates the optional phase-1 metadata pilot. Failure to
// load or verify pilot metadata never takes down the still-supported legacy
// adapter: it logs the degradation and constructs the mux without a shadow.
// The target architecture replaces this temporary fallback with the
// phase-3 validated cache and its explicit stale/fail-closed rules.
func newRuntimeMux(ctx context.Context, cfg config, catalog *Catalog, client *http.Client) *http.ServeMux {
	if cfg.SourceMetadataCacheEnabled {
		cache, err := loadConfiguredSourceMetadataCache(client, cfg)
		if err != nil {
			slog.Error("source metadata cache configuration invalid", "err", err.Error())
			return newMux(cfg, catalog, client, newUnavailableSourceMetadataRuntime(
				cfg.SourceMetadataUsecaseKey,
				cfg.TypeMetadataStorePath,
				err,
			))
		}
		if err := cache.Refresh(ctx, time.Now()); err != nil {
			slog.Error("initial source metadata cache refresh failed; metadata usecase remains fail-closed", "err", err.Error())
		} else {
			slog.Info("source metadata cache activated", "source_oin", cfg.SourceMetadataOIN, "type_id", cfg.SourceMetadataTypeID)
		}
		startSourceMetadataRefresh(ctx, cache, 5*time.Minute)
		return newMux(cfg, catalog, client, cache)
	}
	shadow, err := loadConfiguredSourceMetadataShadow(ctx, client, cfg)
	if err != nil {
		slog.Error("source metadata pilot unavailable; using legacy path", "err", err.Error())
		return newMux(cfg, catalog, client)
	}
	if shadow != nil {
		slog.Info("source metadata shadow enabled", "outway_path", cfg.SourceMetadataOutwayPath, "source_oin", cfg.SourceMetadataOIN, "metadata_version", shadow.Version)
	}
	return newMux(cfg, catalog, client, shadow)
}

// fatal logs and ends the process. main is the only place in this service
// that exits; everything else returns an error.
func fatal(msg string, err error) {
	slog.Error(msg, "err", err.Error())
	os.Exit(1)
}

func main() {
	cfg := loadConfig()
	ctx := context.Background()
	shutdown, err := initTracer(ctx)
	if err != nil {
		slog.Error("tracer init failed", "err", err.Error())
		os.Exit(1)
	}
	defer func() { _ = shutdown(ctx) }()

	catalog, err := loadCatalog(cfg.CatalogPath)
	if err != nil {
		fatal("loading usecase catalog", err)
	}

	client := &http.Client{
		Timeout:   10 * time.Second,
		Transport: otelhttp.NewTransport(http.DefaultTransport),
	}
	// Middleware order: withFscTraceContext wraps otelhttp — the header
	// mutation must happen before otelhttp extracts the parent context.
	srv := &http.Server{
		Addr:              ":" + cfg.Port,
		Handler:           withFscTraceContext(otelhttp.NewHandler(newRuntimeMux(ctx, cfg, catalog, client), "eudi-adapter")),
		ReadHeaderTimeout: readHeaderTimeout,
	}
	slog.Info("eudi-adapter starting", "addr", srv.Addr, "outway", cfg.OutwayURL, "issuer_oin", cfg.IssuerOIN)
	// Previously this logged and returned, so a failure to bind exited 0 and
	// looked like a clean shutdown to the orchestrator.
	fatal("listen and serve", srv.ListenAndServe())
}
