image:
  repository: ghcr.io/ictu/gbo-demo/eudi-adapter
  tag: latest

containerPort: 4009
healthPath: /health

env:
  - name: PORT
    value: "4009"
  - name: FSC_OUTWAY_URL
    value: http://fsc-outway:8080
  - name: SOURCE_REGISTRY_DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: source-registry-reader
        key: uri
  - name: SOURCE_REGISTRY_SCHEMA
    value: source_registry
  - name: SOURCE_REGISTRY_REFRESH_INTERVAL
    value: 5s
